/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("uk.ac.ebi.metabolights.java-conventions")
}

dependencies {
    // api("uk.ac.ebi.arrayexpress2:limpopo-sampletab:1.1.8")
    api("net.sourceforge.javacsv:javacsv:2.0")
    api(project(":metabolights-isatab-utils"))
    api(project(":metabolights-dao"))
}

description = "MetaboLights BioSample DB export"
