ALTER TABLE USER_DETAIL ALTER status SET DEFAULT 'NEW';

ALTER TABLE USER_DETAIL DROP affiliation_url;
ALTER TABLE USER_DETAIL ADD affiliation_url VARCHAR(4000) ;


ALTER TABLE USER_DETAIL ADD CONSTRAINT CHK_USER_STATUS CHECK (status in ('NEW','USER_VERIFIED', 'ACTIVE','FROZEN'));

ALTER TABLE USER_DETAIL ADD CONSTRAINT UQ_USER_EMAIL UNIQUE (email);


INSERT INTO stable_id VALUES (1,'MYSQL',1);