DROP TABLE IF EXISTS REF_METABOLITE;

CREATE TABLE REF_METABOLITE
(
		ID bigint(20) NOT NULL
	,	ACC VARCHAR(50) NOT NULL
	,	NAME VARCHAR(2000) NOT NULL
	,	DESCRIPTION VARCHAR(2000)
	,	INCHI VARCHAR(2000)
	,	TEMP_ID VARCHAR(20)
	,	CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP
	,	UPDATED_DATE TIMESTAMP 
);

ALTER TABLE REF_METABOLITE
ADD CONSTRAINT PK_REF_METABOLITE
PRIMARY KEY (ID);

ALTER TABLE REF_METABOLITE
ADD CONSTRAINT UNIQUE_REF_MET_ACCESSION
UNIQUE (ACC);



-- drop REF_DB
DROP TABLE IF EXISTS REF_DB;

-- create REF_DB
CREATE TABLE REF_DB
(
		ID bigint(20) NOT NULL
	,	DB_NAME VARCHAR(50) NOT NULL
);

ALTER TABLE REF_DB
ADD CONSTRAINT PK_DB
PRIMARY KEY (ID);


-- drop REF_ENTRY
DROP TABLE IF EXISTS REF_ENTRY;
-- create REF_ENTRY
CREATE TABLE REF_ENTRY
(
		ID BIGINT(20) NOT NULL
	,	DB_ID BIGINT(20) NOT NULL
	,	ENTRY_ID VARCHAR(255) NOT NULL
	,	ENTRY_NAME VARCHAR(1000)
	,	REF_MET_ID BIGINT(20)
);
ALTER TABLE REF_ENTRY
ADD CONSTRAINT PK_REF_ENTRY
PRIMARY KEY (ID);

ALTER TABLE REF_ENTRY
ADD CONSTRAINT FK_REF_ENTRY_EL_TYPE
FOREIGN KEY (DB_ID)
REFERENCES REF_DB(ID);

ALTER TABLE REF_ENTRY
ADD CONSTRAINT FK_REF_ENTRY_TO_MET
FOREIGN KEY (REF_MET_ID)
REFERENCES REF_METABOLITE(ID);


/*
-- drop REF_REL_TYPE
DROP TABLE IF EXISTS REF_REL_TYPE;
-- create REF_REL_TYPE
CREATE TABLE REF_REL_TYPE
(
		ID BIGINT(20) NOT NULL
	,	NAME VARCHAR(60) NOT NULL
);

ALTER TABLE REF_REL_TYPE
ADD CONSTRAINT PK_REL_TYPE
PRIMARY KEY (ID);


-- drop REF_XREF
DROP TABLE IF EXISTS REF_XREF;
-- create REF_XREF
CREATE TABLE REF_XREF
(
		ID BIGINT(20) NOT NULL
	,	FROM_ENTRY BIGINT(20) NOT NULL
	,	TO_ENTRY BIGINT(20) NOT NULL
	,	REL_TYPE_ID BIGINT(20) NOT NULL
);
ALTER TABLE REF_XREF
ADD CONSTRAINT PK_REF_XREF
PRIMARY KEY (ID);
ALTER TABLE REF_XREF
ADD CONSTRAINT FK_REF_XREF_REL_TYPE
FOREIGN KEY (REL_TYPE_ID)
REFERENCES REF_REL_TYPE(ID);


*/
