/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("uk.ac.ebi.metabolights.java-conventions")
}

dependencies {
    api(fileTree("libs"))

    api(project(":metabolights-domain"))
    // api("uk.ac.ebi.rhea:rhea-ws-client:2.0.0") 
    api("uk.ac.ebi.biobabel:biobabel-db:1.3.7")
    // api("org.apache.logging.log4j:log4j-api:2.17.2")
    api("org.postgresql:postgresql:42.6.0")
    api("com.googlecode.lambdaj:lambdaj:2.3")
}

repositories {
    flatDir {
        dirs("libs")
    }
}
group = "uk.ac.ebi.metabolights.referencelayer"
description = "MetaboLights Reference layer Data Access Object"
