variables:
  APP_VERSION: "2.1.0"
workflow:
  rules:
    - if: $CI_COMMIT_BRANCH == "test" || $CI_COMMIT_BRANCH == "master" || $CI_COMMIT_BRANCH == "main" || $CI_COMMIT_BRANCH == "staging" || $CI_COMMIT_BRANCH == "development" || $CI_COMMIT_BRANCH == "migration"
stages:
  - build
  - deploy

build_docker:
  stage: build
  script:
    - bash "deployment/steps/build_container.sh"

deploy_editor:
  stage: deploy
  rules:
    - if: $CI_COMMIT_BRANCH == "test" || $CI_COMMIT_BRANCH == "staging" || $CI_COMMIT_BRANCH == "development"
      when: on_success
    - if: $CI_COMMIT_BRANCH == "master" || $CI_COMMIT_BRANCH == "main" || $CI_COMMIT_BRANCH == "migration"
      when: manual
      allow_failure: true
  script:
    - bash "deployment/steps/deploy.sh"
