/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("uk.ac.ebi.metabolights.java-conventions")
}

dependencies {
    api("org.apache.axis2:axis2:1.6.4")
    api("org.apache.axis2:axis2-xmlbeans:1.6.4")
    api("org.apache.xmlbeans:xmlbeans:2.5.0")
    api("org.apache.ws.commons.axiom:axiom-api:1.2.13")
    api("org.apache.ws.commons.axiom:axiom-impl:1.2.13")
    api("wsdl4j:wsdl4j:1.6.2")
    api("org.apache.neethi:neethi:3.0.1")
    api("org.apache.axis2:axis2-transport-local:1.6.4")
    api("org.apache.axis2:axis2-transport-http:1.6.4")
    api("org.apache.ws.commons.schema:XmlSchema:1.4.7")
}

group = "uk.ac.ebi.metabolights.referencelayer"
description = "MetaboLights Reference layer WoRMS-client"
