function ba(c){return function(d){this[c]=d}}function ca(c){return function(){return this[c]}}var a,t=this;function v(c,d,e){c=c.split(".");e=e||t;!(c[0]in e)&&e.execScript&&e.execScript("var "+c[0]);for(var f;c.length&&(f=c.shift());)if(!c.length&&d!==undefined)e[f]=d;else e=e[f]?e[f]:(e[f]={})}function da(c,d){c=c.split(".");d=d||t;for(var e;e=c.shift();)if(d[e])d=d[e];else return null;return d}function ea(){}
function fa(c){var d=typeof c;if(d=="object")if(c){if(c instanceof Array||!(c instanceof Object)&&Object.prototype.toString.call(c)=="[object Array]"||typeof c.length=="number"&&typeof c.splice!="undefined"&&typeof c.propertyIsEnumerable!="undefined"&&!c.propertyIsEnumerable("splice"))return"array";if(!(c instanceof Object)&&(Object.prototype.toString.call(c)=="[object Function]"||typeof c.call!="undefined"&&typeof c.propertyIsEnumerable!="undefined"&&!c.propertyIsEnumerable("call")))return"function"}else return"null";
else if(d=="function"&&typeof c.call=="undefined")return"object";return d}function ga(c){return fa(c)=="array"}function ha(c){var d=fa(c);return d=="array"||d=="object"&&typeof c.length=="number"}function y(c){return typeof c=="string"}function ia(c){return typeof c=="number"}function ja(c){return fa(c)=="function"}function ka(c){c=fa(c);return c=="object"||c=="array"||c=="function"}function la(c){return c[ma]||(c[ma]=++na)}
var ma="closure_uid_"+Math.floor(Math.random()*2147483648).toString(36),na=0;function oa(c,d){var e=d||t;if(arguments.length>2){var f=Array.prototype.slice.call(arguments,2);return function(){var h=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(h,f);return c.apply(e,h)}}else return function(){return c.apply(e,arguments)}}var pa=Date.now||function(){return+new Date};
function qa(c,d){d=d||{};for(var e in d){var f=(""+d[e]).replace(/\$/g,"$$$$");c=c.replace(new RegExp("\\{\\$"+e+"\\}","gi"),f)}return c}function z(c,d){function e(){}e.prototype=d.prototype;c.m=d.prototype;c.prototype=new e;c.prototype.constructor=c};function ra(c){this.b=c}function sa(c){var d=c.b.length-1;return c.b.length>2&&c.b[0]==c.b[d]}
ra.prototype.splice=function(c){var d;var e=c.b;d=this.b.length-1;var f=e.length-1;if(this.b[d]==e[0]||this.b[d]==e[f])d=this.b[d];else if(this.b[0]==e[0]||this.b[0]==e[f])d=this.b[0];else throw"Couldn't splice - no intersection";e=[];f=0;for(var h=this.b.length;f<h;f++)e.push(this.b[f]);this.b[0]==d&&e.reverse();if(c.b[0]==d){f=1;for(h=c.b.length;f<h;f++)e.push(c.b[f])}else for(f=c.b.length-2;f>=0;f--)e.push(c.b[f]);a:{c=1;for(d=e.length-1;c<d;c++)for(f=1;f<d;f++)if(c!=f)if(e[c]==e[f]){c=false;break a}c=
true}if(!c)return null;return new ra(e)};function ta(c){this.stack=(new Error).stack||"";if(c)this.message=String(c)}z(ta,Error);ta.prototype.name="CustomError";function ua(c,d){var e=c.length-d.length;return e>=0&&c.indexOf(d,e)==e}function va(c){for(var d=1;d<arguments.length;d++){var e=String(arguments[d]).replace(/\$/g,"$$$$");c=c.replace(/\%s/,e)}return c}
function wa(c,d){if(d)return c.replace(xa,"&amp;").replace(ya,"&lt;").replace(za,"&gt;").replace(Aa,"&quot;");else{if(!Ba.test(c))return c;if(c.indexOf("&")!=-1)c=c.replace(xa,"&amp;");if(c.indexOf("<")!=-1)c=c.replace(ya,"&lt;");if(c.indexOf(">")!=-1)c=c.replace(za,"&gt;");if(c.indexOf('"')!=-1)c=c.replace(Aa,"&quot;");return c}}var xa=/&/g,ya=/</g,za=/>/g,Aa=/\"/g,Ba=/[&<>\"]/;function Ca(c,d){return(new Array(d+1)).join(c)}
function A(c,d,e){c=e!==undefined?c.toFixed(e):String(c);e=c.indexOf(".");if(e==-1)e=c.length;return Ca("0",Math.max(0,d-e))+c}
function Da(c,d){var e=0;c=String(c).replace(/^[\s\xa0]+|[\s\xa0]+$/g,"").split(".");d=String(d).replace(/^[\s\xa0]+|[\s\xa0]+$/g,"").split(".");for(var f=Math.max(c.length,d.length),h=0;e==0&&h<f;h++){var g=c[h]||"",l=d[h]||"",n=new RegExp("(\\d*)(\\D*)","g"),m=new RegExp("(\\d*)(\\D*)","g");do{var o=n.exec(g)||["","",""],q=m.exec(l)||["","",""];if(o[0].length==0&&q[0].length==0)break;e=Ea(o[1].length==0?0:parseInt(o[1],10),q[1].length==0?0:parseInt(q[1],10))||Ea(o[2].length==0,q[2].length==0)||
Ea(o[2],q[2])}while(e==0)}return e}function Ea(c,d){if(c<d)return-1;else if(c>d)return 1;return 0}var Fa=Math.random()*2147483648|0;function Ga(c,d){d.unshift(c);ta.call(this,va.apply(null,d));d.shift();this.Yf=c}z(Ga,ta);Ga.prototype.name="AssertionError";function Ha(c,d,e,f){var h="Assertion failed";if(e){h+=": "+e;var g=f}else if(c){h+=": "+c;g=d}throw new Ga(""+h,g||[]);}function Ia(c,d){!c&&Ha("",null,d,Array.prototype.slice.call(arguments,2));return c}function Ja(c){throw new Ga("Failure"+(c?": "+c:""),Array.prototype.slice.call(arguments,1));};var B=Array.prototype,Ka=B.indexOf?function(c,d,e){Ia(c.length!=null);return B.indexOf.call(c,d,e)}:function(c,d,e){e=e==null?0:e<0?Math.max(0,c.length+e):e;if(y(c)){if(!y(d)||d.length!=1)return-1;return c.indexOf(d,e)}for(e=e;e<c.length;e++)if(e in c&&c[e]===d)return e;return-1},C=B.forEach?function(c,d,e){Ia(c.length!=null);B.forEach.call(c,d,e)}:function(c,d,e){for(var f=c.length,h=y(c)?c.split(""):c,g=0;g<f;g++)g in h&&d.call(e,h[g],g,c)},La=B.filter?function(c,d,e){Ia(c.length!=null);return B.filter.call(c,
d,e)}:function(c,d,e){for(var f=c.length,h=[],g=0,l=y(c)?c.split(""):c,n=0;n<f;n++)if(n in l){var m=l[n];if(d.call(e,m,n,c))h[g++]=m}return h},D=B.map?function(c,d,e){Ia(c.length!=null);return B.map.call(c,d,e)}:function(c,d,e){for(var f=c.length,h=new Array(f),g=y(c)?c.split(""):c,l=0;l<f;l++)if(l in g)h[l]=d.call(e,g[l],l,c);return h};function Ma(c,d,e,f){if(c.reduce)return f?c.reduce(oa(d,f),e):c.reduce(d,e);var h=e;C(c,function(g,l){h=d.call(f,h,g,l,c)});return h}
function Na(c,d,e){a:{for(var f=c.length,h=y(c)?c.split(""):c,g=0;g<f;g++)if(g in h&&d.call(e,h[g],g,c)){d=g;break a}d=-1}return d<0?null:y(c)?c.charAt(d):c[d]}function E(c,d){return Ka(c,d)>=0}function Oa(c,d,e){Pa(c,e,0,d)}function Qa(c,d){d=Ka(c,d);var e;if(e=d>=0)Ra(c,d);return e}function Ra(c,d){Ia(c.length!=null);return B.splice.call(c,d,1).length==1}function Sa(){return B.concat.apply(B,arguments)}
function Ta(c){if(ga(c))return Sa(c);else{for(var d=[],e=0,f=c.length;e<f;e++)d[e]=c[e];return d}}function Pa(c){Ia(c.length!=null);return B.splice.apply(c,Ua(arguments,1))}function Ua(c,d,e){Ia(c.length!=null);return arguments.length<=2?B.slice.call(c,d):B.slice.call(c,d,e)}function Va(c,d){return c>d?1:c<d?-1:0}function Wa(c,d){for(var e=[],f=0;f<d;f++)e[f]=c;return e}
function Xa(){for(var c=[],d=0;d<arguments.length;d++){var e=arguments[d];ga(e)?c.push.apply(c,Xa.apply(null,e)):c.push(e)}return c};function Ya(c){c=c%360;return c*360<0?c+360:c}function F(c){return c*Math.PI/180};function Za(c,d,e,f,h,g){if(arguments.length==6)this.setTransform(c,d,e,f,h,g);else if(arguments.length!=0)throw Error("Insufficient matrix parameters");else{this.p=this.J=1;this.A=this.G=this.W=this.X=0}}a=Za.prototype;a.K=function(){return new Za(this.p,this.A,this.G,this.J,this.W,this.X)};a.setTransform=function(c,d,e,f,h,g){if(!ia(c)||!ia(d)||!ia(e)||!ia(f)||!ia(h)||!ia(g))throw Error("Invalid transform parameters");this.p=c;this.A=d;this.G=e;this.J=f;this.W=h;this.X=g;return this};
a.scale=function(c,d){this.p*=c;this.A*=c;this.G*=d;this.J*=d;return this};a.translate=function(c,d){this.W+=c*this.p+d*this.G;this.X+=c*this.A+d*this.J;return this};a.rotate=function(c,d,e){c=$a(new Za,c,d,e);d=this.p;e=this.G;this.p=c.p*d+c.A*e;this.G=c.G*d+c.J*e;this.W+=c.W*d+c.X*e;d=this.A;e=this.J;this.A=c.p*d+c.A*e;this.J=c.G*d+c.J*e;this.X+=c.W*d+c.X*e;return this};a.toString=function(){return"matrix("+[this.p,this.A,this.G,this.J,this.W,this.X].join(",")+")"};
a.transform=function(c,d,e,f,h){var g=d;f=f;for(d=d+2*h;g<d;){h=c[g++];var l=c[g++];e[f++]=h*this.p+l*this.G+this.W;e[f++]=h*this.A+l*this.J+this.X}};a.Cc=function(){var c=this.p*this.J-this.G*this.A;return new Za(this.J/c,-this.A/c,-this.G/c,this.p/c,(this.G*this.X-this.J*this.W)/c,(this.A*this.W-this.p*this.X)/c)};function ab(c,d,e){return c.setTransform(d,0,0,e,0,0)}function $a(c,d,e,f){var h=Math.cos(d);d=Math.sin(d);return c.setTransform(h,d,-d,h,e-e*h+f*d,f-e*d-f*h)};function G(c,d,e,f,h,g){Za.call(this);arguments.length==6&&this.setTransform(c,d,e,f,h,g)}z(G,Za);function H(c,d){d=D(d,function(f){return[f.x,f.y]});var e=Xa(d);d=[];c.transform(e,0,d,0,e.length/2);c=[];for(e=0;e<d.length;e+=2)c.push(new I(d[e],d[e+1]));return c}function bb(c,d){return H(c,d)}G.prototype.Cc=function(){var c=this.p*this.J-this.G*this.A;return new G(this.J/c,-this.A/c,-this.G/c,this.p/c,(this.G*this.X-this.J*this.W)/c,(this.A*this.W-this.p*this.X)/c)};function cb(c){return function(){return c}}var db=cb(false);function eb(c,d,e){for(var f in c)d.call(e,c[f],f,c)}function fb(c){var d=[],e=0;for(var f in c)d[e++]=c[f];return d}function gb(c){var d=[],e=0;for(var f in c)d[e++]=f;return d}function hb(c,d){var e;if(e=d in c)delete c[d];return e}function ib(c,d,e){if(d in c)return c[d];return e}function jb(c){var d={};for(var e in c)d[c[e]]=e;return d}var kb=["constructor","hasOwnProperty","isPrototypeOf","propertyIsEnumerable","toLocaleString","toString","valueOf"];
function lb(c){for(var d,e,f=1;f<arguments.length;f++){e=arguments[f];for(d in e)c[d]=e[d];for(var h=0;h<kb.length;h++){d=kb[h];if(Object.prototype.hasOwnProperty.call(e,d))c[d]=e[d]}}}function mb(){var c=arguments.length;if(c==1&&ga(arguments[0]))return mb.apply(null,arguments[0]);for(var d={},e=0;e<c;e++)d[arguments[e]]=true;return d};function nb(c){if(typeof c.V=="function")return c.V();if(y(c))return c.split("");if(ha(c)){for(var d=[],e=c.length,f=0;f<e;f++)d.push(c[f]);return d}return fb(c)}function ob(c,d,e){if(typeof c.forEach=="function")c.forEach(d,e);else if(ha(c)||y(c))C(c,d,e);else{var f;if(typeof c.dc=="function")f=c.dc();else if(typeof c.V!="function")if(ha(c)||y(c)){f=[];for(var h=c.length,g=0;g<h;g++)f.push(g);f=f}else f=gb(c);else f=void 0;h=nb(c);g=h.length;for(var l=0;l<g;l++)d.call(e,h[l],f&&f[l],c)}};function J(c){this.M={};this.j=[];var d=arguments.length;if(d>1){if(d%2)throw Error("Uneven number of arguments");for(var e=0;e<d;e+=2)this.u(arguments[e],arguments[e+1])}else c&&this.La(c)}a=J.prototype;a.i=0;a.vc=0;a.ub=ca("i");a.V=function(){pb(this);for(var c=[],d=0;d<this.j.length;d++)c.push(this.M[this.j[d]]);return c};a.dc=function(){pb(this);return this.j.concat()};a.clear=function(){this.M={};this.vc=this.i=this.j.length=0};
a.remove=function(c){if(Object.prototype.hasOwnProperty.call(this.M,c)){delete this.M[c];this.i--;this.vc++;this.j.length>2*this.i&&pb(this);return true}return false};function pb(c){if(c.i!=c.j.length){for(var d=0,e=0;d<c.j.length;){var f=c.j[d];if(Object.prototype.hasOwnProperty.call(c.M,f))c.j[e++]=f;d++}c.j.length=e}if(c.i!=c.j.length){var h={};for(e=d=0;d<c.j.length;){f=c.j[d];if(!Object.prototype.hasOwnProperty.call(h,f)){c.j[e++]=f;h[f]=1}d++}c.j.length=e}}
J.prototype.f=function(c,d){if(Object.prototype.hasOwnProperty.call(this.M,c))return this.M[c];return d};J.prototype.u=function(c,d){if(!Object.prototype.hasOwnProperty.call(this.M,c)){this.i++;this.j.push(c);this.vc++}this.M[c]=d};J.prototype.La=function(c){var d;if(c instanceof J){d=c.dc();c=c.V()}else{d=gb(c);c=fb(c)}for(var e=0;e<d.length;e++)this.u(d[e],c[e])};J.prototype.K=function(){return new J(this)};function qb(c){this.M=new J;c&&this.La(c)}function rb(c){var d=typeof c;return d=="object"&&c||d=="function"?"o"+la(c):d.substr(0,1)+c}a=qb.prototype;a.ub=function(){return this.M.ub()};a.add=function(c){this.M.u(rb(c),c)};a.La=function(c){c=nb(c);for(var d=c.length,e=0;e<d;e++)this.add(c[e])};a.Lb=function(c){c=nb(c);for(var d=c.length,e=0;e<d;e++)this.remove(c[e])};a.remove=function(c){return this.M.remove(rb(c))};a.clear=function(){this.M.clear()};a.V=function(){return this.M.V()};a.K=function(){return new qb(this)};function sb(c){return tb(c||arguments.callee.caller,[])}
function tb(c,d){var e=[];if(E(d,c))e.push("[...circular reference...]");else if(c&&d.length<50){e.push(ub(c)+"(");for(var f=c.arguments,h=0;h<f.length;h++){h>0&&e.push(", ");var g;g=f[h];switch(typeof g){case "object":g=g?"object":"null";break;case "string":g=g;break;case "number":g=String(g);break;case "boolean":g=g?"true":"false";break;case "function":g=(g=ub(g))?g:"[fn]";break;case "undefined":default:g=typeof g;break}if(g.length>40)g=g.substr(0,40)+"...";e.push(g)}d.push(c);e.push(")\n");try{e.push(tb(c.caller,
d))}catch(l){e.push("[exception trying to get caller]\n")}}else c?e.push("[...long stack...]"):e.push("[end]");return e.join("")}function ub(c){c=String(c);if(!vb[c]){var d=/function ([^\(]+)/.exec(c);vb[c]=d?d[1]:"[Anonymous]"}return vb[c]}var vb={};function wb(c,d,e,f,h){this.reset(c,d,e,f,h)}wb.prototype.Ue=0;wb.prototype.Lc=null;wb.prototype.Kc=null;var xb=0;wb.prototype.reset=function(c,d,e,f,h){this.Ue=typeof h=="number"?h:xb++;this.fg=f||pa();this.jb=c;this.Zf=d;this.Xf=e;delete this.Lc;delete this.Kc};wb.prototype.jd=ba("jb");function yb(c){this.Le=c}yb.prototype.ha=null;yb.prototype.jb=null;yb.prototype.r=null;yb.prototype.Sc=null;function zb(c,d){this.name=c;this.value=d}zb.prototype.toString=ca("name");var Ab=new zb("SEVERE",1E3),Bb=new zb("WARNING",900),Cb=new zb("INFO",800),Db=new zb("CONFIG",700),Eb=new zb("FINE",500);yb.prototype.jd=ba("jb");function Fb(c){if(c.jb)return c.jb;if(c.ha)return Fb(c.ha);Ja("Root logger has no level set.");return null}
yb.prototype.log=function(c,d,e){c.value>=Fb(this).value&&Gb(this,this.me(c,d,e))};
yb.prototype.me=function(c,d,e){var f=new wb(c,String(d),this.Le);if(e){f.Lc=e;var h;var g=arguments.callee.caller;try{var l,n=da("window.location.href");l=typeof e=="string"?{message:e,name:"Unknown error",lineNumber:"Not available",fileName:n,stack:"Not available"}:!e.lineNumber||!e.fileName||!e.stack?{message:e.message,name:e.name,lineNumber:e.lineNumber||e.Wf||"Not available",fileName:e.fileName||e.filename||e.sourceURL||n,stack:e.stack||"Not available"}:e;h="Message: "+wa(l.message)+'\nUrl: <a href="view-source:'+
l.fileName+'" target="_new">'+l.fileName+"</a>\nLine: "+l.lineNumber+"\n\nBrowser stack:\n"+wa(l.stack+"-> ")+"[end]\n\nJS stack traversal:\n"+wa(sb(g)+"-> ")}catch(m){h="Exception trying to expose exception! You win, we lose. "+m}f.Kc=h}return f};function Hb(c,d,e){c.log(Ab,d,e)}yb.prototype.info=function(c,d){this.log(Cb,c,d)};yb.prototype.c=function(c,d){this.log(Db,c,d)};function Gb(c,d){for(c=c;c;){var e=c;if(e.Sc)for(var f=0,h=void 0;h=e.Sc[f];f++)h(d);c=c.ha}}var Ib={},Jb=null;
function Kb(c){if(!Jb){Jb=new yb("");Ib[""]=Jb;Jb.jd(Db)}return Ib[c]||Lb(c)}function Lb(c){var d=new yb(c),e=c.lastIndexOf("."),f=c.substr(0,e);e=c.substr(e+1);f=Kb(f);if(!f.r)f.r={};f.r[e]=d;d.ha=f;return Ib[c]=d};var Mb,Nb,Ob,Pb,Qb,Rb;function Sb(){return t.navigator?t.navigator.userAgent:null}Qb=Pb=Ob=Nb=Mb=false;var Tb;if(Tb=Sb()){var Ub=t.navigator;Mb=Tb.indexOf("Opera")==0;Nb=!Mb&&Tb.indexOf("MSIE")!=-1;Pb=(Ob=!Mb&&Tb.indexOf("WebKit")!=-1)&&Tb.indexOf("Mobile")!=-1;Qb=!Mb&&!Ob&&Ub.product=="Gecko"}var Vb=Mb,L=Nb,M=Qb,Wb=Ob,Xb=Pb,Yb,Zb=t.navigator;Yb=Zb&&Zb.platform||"";Rb=Yb.indexOf("Mac")!=-1;var $b=Yb.indexOf("Win")!=-1,ac;
a:{var bc="",cc;if(Vb&&t.opera){var dc=t.opera.version;bc=typeof dc=="function"?dc():dc}else{if(M)cc=/rv\:([^\);]+)(\)|;)/;else if(L)cc=/MSIE\s+([^\);]+)(\)|;)/;else if(Wb)cc=/WebKit\/(\S+)/;if(cc){var ec=cc.exec(Sb());bc=ec?ec[1]:""}}if(L){var fc,gc=t.document;fc=gc?gc.documentMode:undefined;if(fc>parseFloat(bc)){ac=String(fc);break a}}ac=bc}var hc={};function N(c){return hc[c]||(hc[c]=Da(ac,c)>=0)};var ic=[];var jc;!L||N("9");var kc=L&&!N("8");function lc(){}lc.prototype.Hc=false;lc.prototype.pa=function(){if(!this.Hc){this.Hc=true;this.k()}};lc.prototype.k=function(){};function mc(c,d){this.type=c;this.currentTarget=this.target=d}z(mc,lc);a=mc.prototype;a.k=function(){delete this.type;delete this.target;delete this.currentTarget};a.Ga=false;a.mb=true;a.stopPropagation=function(){this.Ga=true};a.preventDefault=function(){this.mb=false};function nc(c,d){c&&this.zb(c,d)}z(nc,mc);a=nc.prototype;a.target=null;a.relatedTarget=null;a.offsetX=0;a.offsetY=0;a.clientX=0;a.clientY=0;a.screenX=0;a.screenY=0;a.button=0;a.keyCode=0;a.charCode=0;a.ctrlKey=false;a.altKey=false;a.shiftKey=false;a.metaKey=false;a.Oe=false;a.Ra=null;
a.zb=function(c,d){var e=this.type=c.type;this.target=c.target||c.srcElement;this.currentTarget=d;if(d=c.relatedTarget){if(M)try{d=d.nodeName&&d}catch(f){d=null}}else if(e=="mouseover")d=c.fromElement;else if(e=="mouseout")d=c.toElement;this.relatedTarget=d;this.offsetX=c.offsetX!==undefined?c.offsetX:c.layerX;this.offsetY=c.offsetY!==undefined?c.offsetY:c.layerY;this.clientX=c.clientX!==undefined?c.clientX:c.pageX;this.clientY=c.clientY!==undefined?c.clientY:c.pageY;this.screenX=c.screenX||0;this.screenY=
c.screenY||0;this.button=c.button;this.keyCode=c.keyCode||0;this.charCode=c.charCode||(e=="keypress"?c.keyCode:0);this.ctrlKey=c.ctrlKey;this.altKey=c.altKey;this.shiftKey=c.shiftKey;this.metaKey=c.metaKey;this.Oe=Rb?c.metaKey:c.ctrlKey;this.Ra=c;delete this.mb;delete this.Ga};a.stopPropagation=function(){nc.m.stopPropagation.call(this);if(this.Ra.stopPropagation)this.Ra.stopPropagation();else this.Ra.cancelBubble=true};
a.preventDefault=function(){nc.m.preventDefault.call(this);var c=this.Ra;if(c.preventDefault)c.preventDefault();else{c.returnValue=false;if(kc)try{if(c.ctrlKey||c.keyCode>=112&&c.keyCode<=123)c.keyCode=-1}catch(d){}}};a.k=function(){nc.m.k.call(this);this.relatedTarget=this.currentTarget=this.target=this.Ra=null};function oc(){}var pc=0;a=oc.prototype;a.key=0;a.Xa=false;a.Bc=false;a.zb=function(c,d,e,f,h,g){if(ja(c))this.Wc=true;else if(c&&c.handleEvent&&ja(c.handleEvent))this.Wc=false;else throw Error("Invalid listener argument");this.Va=c;this.cd=d;this.src=e;this.type=f;this.capture=!!h;this.wb=g;this.Bc=false;this.key=++pc;this.Xa=false};a.handleEvent=function(c){if(this.Wc)return this.Va.call(this.wb||this.src,c);return this.Va.handleEvent.call(this.Va,c)};var qc;var rc=(qc="ScriptEngine"in t&&t.ScriptEngine()=="JScript")?t.ScriptEngineMajorVersion()+"."+t.ScriptEngineMinorVersion()+"."+t.ScriptEngineBuildVersion():"0";function sc(c,d){this.Zc=d;this.Da=[];if(c>this.Zc)throw Error("[goog.structs.SimplePool] Initial cannot be greater than max");for(d=0;d<c;d++)this.Da.push(this.oa?this.oa():{})}z(sc,lc);sc.prototype.oa=null;sc.prototype.Gc=null;function tc(c){if(c.Da.length)return c.Da.pop();return c.oa?c.oa():{}}function uc(c,d){c.Da.length<c.Zc?c.Da.push(d):vc(c,d)}function vc(c,d){if(c.Gc)c.Gc(d);else if(ka(d))if(ja(d.pa))d.pa();else for(var e in d)delete d[e]}
sc.prototype.k=function(){sc.m.k.call(this);for(var c=this.Da;c.length;)vc(this,c.pop());delete this.Da};var wc,xc,yc,zc,Ac,Bc,Dc,Ec,Fc,Gc,Hc;
(function(){function c(){return{i:0,ia:0}}function d(){return[]}function e(){function u(w){return l.call(u.src,u.key,w)}return u}function f(){return new oc}function h(){return new nc}var g=qc&&!(Da(rc,"5.7")>=0),l;Bc=function(u){l=u};if(g){wc=function(){return tc(n)};xc=function(u){uc(n,u)};yc=function(){return tc(m)};zc=function(u){uc(m,u)};Ac=function(){return tc(o)};Dc=function(){uc(o,e())};Ec=function(){return tc(q)};Fc=function(u){uc(q,u)};Gc=function(){return tc(s)};Hc=function(u){uc(s,u)};
var n=new sc(0,600);n.oa=c;var m=new sc(0,600);m.oa=d;var o=new sc(0,600);o.oa=e;var q=new sc(0,600);q.oa=f;var s=new sc(0,600);s.oa=h}else{wc=c;xc=ea;yc=d;zc=ea;Ac=e;Dc=ea;Ec=f;Fc=ea;Gc=h;Hc=ea}})();var Ic={},O={},Jc={},Kc={};
function Lc(c,d,e,f,h){if(d)if(ga(d)){for(var g=0;g<d.length;g++)Lc(c,d[g],e,f,h);return null}else{f=!!f;var l=O;d in l||(l[d]=wc());l=l[d];if(!(f in l)){l[f]=wc();l.i++}l=l[f];var n=la(c),m;l.ia++;if(l[n]){m=l[n];for(g=0;g<m.length;g++){l=m[g];if(l.Va==e&&l.wb==h){if(l.Xa)break;return m[g].key}}}else{m=l[n]=yc();l.i++}g=Ac();g.src=c;l=Ec();l.zb(e,g,c,d,f,h);e=l.key;g.key=e;m.push(l);Ic[e]=l;Jc[n]||(Jc[n]=yc());Jc[n].push(l);if(c.addEventListener){if(c==t||!c.Wb)c.addEventListener(d,g,f)}else c.attachEvent(Mc(d),
g);return e}else throw Error("Invalid event type");}function Nc(c,d,e,f,h){if(ga(d)){for(var g=0;g<d.length;g++)Nc(c,d[g],e,f,h);return null}f=!!f;c=Oc(c,d,f);if(!c)return false;for(g=0;g<c.length;g++)if(c[g].Va==e&&c[g].capture==f&&c[g].wb==h)return Pc(c[g].key);return false}
function Pc(c){if(!Ic[c])return false;var d=Ic[c];if(d.Xa)return false;var e=d.src,f=d.type,h=d.cd,g=d.capture;if(e.removeEventListener){if(e==t||!e.Wb)e.removeEventListener(f,h,g)}else e.detachEvent&&e.detachEvent(Mc(f),h);e=la(e);h=O[f][g][e];if(Jc[e]){var l=Jc[e];Qa(l,d);l.length==0&&delete Jc[e]}d.Xa=true;h.bd=true;Qc(f,g,e,h);delete Ic[c];return true}
function Qc(c,d,e,f){if(!f.Hb)if(f.bd){for(var h=0,g=0;h<f.length;h++)if(f[h].Xa){var l=f[h].cd;l.src=null;Dc(l);Fc(f[h])}else{if(h!=g)f[g]=f[h];g++}f.length=g;f.bd=false;if(g==0){zc(f);delete O[c][d][e];O[c][d].i--;if(O[c][d].i==0){xc(O[c][d]);delete O[c][d];O[c].i--}if(O[c].i==0){xc(O[c]);delete O[c]}}}}
function Rc(c,d,e){var f=0,h=c==null,g=d==null,l=e==null;e=!!e;if(h)eb(Jc,function(m){for(var o=m.length-1;o>=0;o--){var q=m[o];if((g||d==q.type)&&(l||e==q.capture)){Pc(q.key);f++}}});else{c=la(c);if(Jc[c]){c=Jc[c];for(h=c.length-1;h>=0;h--){var n=c[h];if((g||d==n.type)&&(l||e==n.capture)){Pc(n.key);f++}}}}return f}function Oc(c,d,e){var f=O;if(d in f){f=f[d];if(e in f){f=f[e];c=la(c);if(f[c])return f[c]}}return null}function Mc(c){if(c in Kc)return Kc[c];return Kc[c]="on"+c}
function Sc(c,d,e,f,h){var g=1;d=la(d);if(c[d]){c.ia--;c=c[d];if(c.Hb)c.Hb++;else c.Hb=1;try{for(var l=c.length,n=0;n<l;n++){var m=c[n];if(m&&!m.Xa)g&=Tc(m,h)!==false}}finally{c.Hb--;Qc(e,f,d,c)}}return Boolean(g)}function Tc(c,d){d=c.handleEvent(d);c.Bc&&Pc(c.key);return d}
function Uc(c,d){if(!Ic[c])return true;c=Ic[c];var e=c.type,f=O;if(!(e in f))return true;f=f[e];var h,g;if(jc===undefined)jc=L&&!t.addEventListener;if(jc){h=d||da("window.event");d=true in f;var l=false in f;if(d){if(h.keyCode<0||h.returnValue!=undefined)return true;a:{var n=false;if(h.keyCode==0)try{h.keyCode=-1;break a}catch(m){n=true}if(n||h.returnValue==undefined)h.returnValue=true}}n=Gc();n.zb(h,this);h=true;try{if(d){for(var o=yc(),q=n.currentTarget;q;q=q.parentNode)o.push(q);g=f[true];g.ia=
g.i;for(var s=o.length-1;!n.Ga&&s>=0&&g.ia;s--){n.currentTarget=o[s];h&=Sc(g,o[s],e,true,n)}if(l){g=f[false];g.ia=g.i;for(s=0;!n.Ga&&s<o.length&&g.ia;s++){n.currentTarget=o[s];h&=Sc(g,o[s],e,false,n)}}}else h=Tc(c,n)}finally{if(o){o.length=0;zc(o)}n.pa();Hc(n)}return h}g=new nc(d,this);try{h=Tc(c,g)}finally{g.pa()}return h}Bc(Uc);ic[ic.length]=function(c){Uc=c(Uc);Bc(Uc)};function Vc(){}z(Vc,lc);a=Vc.prototype;a.Wb=true;a.Jb=null;a.pc=ba("Jb");a.addEventListener=function(c,d,e,f){Lc(this,c,d,e,f)};a.removeEventListener=function(c,d,e,f){Nc(this,c,d,e,f)};
a.dispatchEvent=function(c){c=c;if(y(c))c=new mc(c,this);else if(c instanceof mc)c.target=c.target||this;else{var d=c;c=new mc(c.type,this);lb(c,d)}d=1;var e,f=c.type,h=O;if(f in h){h=h[f];f=true in h;var g;if(f){e=[];for(g=this;g;g=g.Jb)e.push(g);g=h[true];g.ia=g.i;for(var l=e.length-1;!c.Ga&&l>=0&&g.ia;l--){c.currentTarget=e[l];d&=Sc(g,e[l],c.type,true,c)&&c.mb!=false}}if(false in h){g=h[false];g.ia=g.i;if(f)for(l=0;!c.Ga&&l<e.length&&g.ia;l++){c.currentTarget=e[l];d&=Sc(g,e[l],c.type,false,c)&&
c.mb!=false}else for(e=this;!c.Ga&&e&&g.ia;e=e.Jb){c.currentTarget=e;d&=Sc(g,e,c.type,false,c)&&c.mb!=false}}c=Boolean(d)}else c=true;return c};a.k=function(){Vc.m.k.call(this);Rc(this);this.Jb=null};/*
 Copyright 2010 Paul Novak (paul@wingu.com)

 Licensed under the Apache License, Version 2.0 (the "License"); you may not
 use this file except in compliance with the License. You may obtain a copy of
 the License at

 http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 License for the specific language governing permissions and limitations under
 the License.
*/
function Wc(){this.ac=this.Rd()}z(Wc,Vc);Wc.prototype.Rd=db;function Xc(c,d){c.s=d;C([],function(e){d.mc(e.id,e.key)})}function Yc(c,d){if(c.s==d)c.ac=true;else Hb(c.n,"Trying to enable an unregistered field with this plugin.")}function Zc(c,d){c.n.info("disable");if(c.s==d)c.ac=false;else Hb(c.n,"Trying to disable an unregistered field with this plugin.")}Wc.prototype.n=Kb("specview.controller.Plugin");Wc.prototype.k=function(){this.s&&$c(this,this.s);Wc.m.k.call(this)};
function $c(c){if(c.s){Zc(c,c.s);c.s=null}}Wc.prototype.Zd=true;var ad={};Wc.prototype.Sd=db;var bd=jb({Gf:1,Hf:2,Jf:3,Uf:4,Lf:5,execCommand:6,queryCommandValue:7,Mf:8,Pf:9,Of:10,Nf:11,Be:12,Bf:{}.df,Af:14,zf:15,Ef:16,Df:17,Cf:18,yf:19,xf:20,wf:21,Tf:22,Sf:23,Rf:24,Qf:25,Ff:26});Wc.prototype.execCommand=function(c){var d=this.Ge(c);try{cd(this.s);var e=this.qf.apply(this,arguments)}finally{if(!d){d=this.s;d.Xc=true;d.Vc=true;this.s.dispatchEvent(dd)}}return e};Wc.prototype.Ge=db;function ed(){Wc.call(this)}z(ed,Wc);v("specview.controller.plugins.Highlight",ed,void 0);a=ed.prototype;a.we=cb("highlight");a.zc="#4E9600";a.n=Kb("specview.controller.plugins.Highlight");a.Eb=null;a.Fb=null;a.za=null;
a.Be=function(c){if(fd(this.s,c)){this.s.selected.length=0;var d=fd(this.s,c);if(d instanceof P){if(this.Eb==null||d!=this.Eb){this.za!=null&&this.za.xb.clear();this.Eb=d;this.za=c.currentTarget;this.s.selected.push(d);c.currentTarget.xb=this.s.Ib.Tb.Sa(d,this.zc)}return true}else if(d instanceof Q){if(this.Fb==null||d!=this.Fb){this.za!=null&&this.za.xb.clear();this.Fb=d;this.za=c.currentTarget;this.s.selected.push(d);c.currentTarget.xb=this.s.Ib.Ub.f(d).Sa(d,this.zc)}return true}}else if(this.za!=
null){this.za.xb.clear();this.Fb=this.Eb=null}return false};function gd(){this.na=[]}gd.prototype.n=Kb("specview.graphics.ElementArray");gd.prototype.add=function(c){Ia(c instanceof R);this.na.push(c);return this};gd.prototype.clear=function(){C(this.na,function(c){hd(c.e())},this);this.na.length=0};var id={C:4,Si:4,N:3,P:3,O:2,S:2,H:1};var jd={};function kd(c,d){this.b=c;this.g=d;this.he=new Array(3);this.Sb=null}kd.prototype.la=function(){if(!this.Sb){for(var c=0,d=0,e=0,f=this.b.length;e<f;e++){c+=this.b[e].a.x;d+=this.b[e].a.y}this.Sb=new I(c/this.b.length,d/this.b.length)}return this.Sb};kd.prototype.toString=function(){return"specview.ring.Ring \n\t"+D(this.b,function(c){return" "+c.toString()},this).join("\n\t")+"\n\t"+D(this.g,function(c){return" "+c.toString()},this).join("\n\t")+"\n\t"};function ld(c){this.qa=[];this.b=[];for(var d=0,e=c.$();d<e;d++){bond=c.g[d];this.qa.push(new ra([bond.source,bond.target]))}d=0;for(e=c.b.length;d<e;d++)this.b.push(c.o(d))}
ld.prototype.remove=function(c,d){for(var e=[],f=0,h=this.qa.length;f<h;f++){var g=this.qa[f];if(sa(g))E(g.b,c)&&e.push(g);else{var l=g.b.length-1;if(g.b[0]==c||g.b[l]==c)e.push(g)}}f=[];g=0;for(l=e.length;g<l;g++)sa(e[g])&&f.push(e[g]);g=0;for(l=f.length;g<l;g++){E(e,f[g])&&Qa(e,f[g]);E(this.qa,f[g])&&Qa(this.qa,f[g])}h=[];g=0;for(l=e.length;g<l;g++)for(var n=g+1;n<l;n++){var m=e[n].splice(e[g]);m!=null&&h.push(m)}g=0;for(l=e.length;g<l;g++)E(this.qa,e[g])&&Qa(this.qa,e[g]);g=0;for(l=h.length;g<
l;g++)!E(this.qa,h[g])&&h[g].b.length<=d+1&&this.qa.push(h[g]);Qa(this.b,c);return f};function md(c,d){this.Bb=c||1;this.ob=d||nd;this.Vb=oa(this.Xe,this);this.hc=pa()}z(md,Vc);md.prototype.enabled=false;var nd=t.window;a=md.prototype;a.Ka=null;a.Xe=function(){if(this.enabled){var c=pa()-this.hc;if(c>0&&c<this.Bb*0.8)this.Ka=this.ob.setTimeout(this.Vb,this.Bb-c);else{this.dispatchEvent(od);if(this.enabled){this.Ka=this.ob.setTimeout(this.Vb,this.Bb);this.hc=pa()}}}};a.start=function(){this.enabled=true;if(!this.Ka){this.Ka=this.ob.setTimeout(this.Vb,this.Bb);this.hc=pa()}};
a.stop=function(){this.enabled=false;if(this.Ka){this.ob.clearTimeout(this.Ka);this.Ka=null}};a.k=function(){md.m.k.call(this);this.stop();delete this.ob};var od="tick";function pd(c,d,e){if(ja(c)){if(e)c=oa(c,e)}else if(c&&typeof c.handleEvent=="function")c=oa(c.handleEvent,c);else throw Error("Invalid listener argument");return d>2147483647?-1:nd.setTimeout(c,d||0)};var qd={8:"backspace",9:"tab",13:"enter",16:"shift",17:"ctrl",18:"alt",19:"pause",20:"caps-lock",27:"esc",32:"space",33:"pg-up",34:"pg-down",35:"end",36:"home",37:"left",38:"up",39:"right",40:"down",45:"insert",46:"delete",48:"0",49:"1",50:"2",51:"3",52:"4",53:"5",54:"6",55:"7",56:"8",57:"9",61:"equals",65:"a",66:"b",67:"c",68:"d",69:"e",70:"f",71:"g",72:"h",73:"i",74:"j",75:"k",76:"l",77:"m",78:"n",79:"o",80:"p",81:"q",82:"r",83:"s",84:"t",85:"u",86:"v",87:"w",88:"x",89:"y",90:"z",93:"context",96:"num-0",
97:"num-1",98:"num-2",99:"num-3",100:"num-4",101:"num-5",102:"num-6",103:"num-7",104:"num-8",105:"num-9",106:"num-multiply",107:"num-plus",109:"num-minus",110:"num-period",111:"num-division",112:"f1",113:"f2",114:"f3",115:"f4",116:"f5",117:"f6",118:"f7",119:"f8",120:"f9",121:"f10",122:"f11",123:"f12",187:"equals",188:",",190:".",191:"/",220:"\\",224:"win"};function rd(c){this.nb={};this.ta={Ia:[],sd:0};this.xe=mb(sd);this.Vd=true;this.Ud=this.Wd=false;this.Ke=true;this.sa=c;Lc(this.sa,"keydown",this.hb,false,this);Rb&&M&&N("1.8")&&Lc(this.sa,"keyup",this.Oc,false,this);if($b&&!M){Lc(this.sa,"keypress",this.Qc,false,this);Lc(this.sa,"keyup",this.Rc,false,this)}}var td;z(rd,Vc);var sd=[27,112,113,114,115,116,117,118,119,120,121,122,123,19],ud={Fd:"shortcut",Ed:"shortcut_"};rd.prototype.mc=function(c){vd(this.nb,wd(this,1,arguments),c)};
function wd(c,d,e){if(y(e[d])){d=e[d];d=d.replace(/[ +]*\+[ +]*/g,"+").replace(/[ ]+/g," ").toLowerCase();d=d.split(" ");e=[];var f;for(c=0;f=d[c];c++){var h=f.split("+"),g;f=0;for(var l,n=0;l=h[n];n++){switch(l){case "shift":f|=1;continue;case "ctrl":f|=2;continue;case "alt":f|=4;continue;case "meta":f|=8;continue}g=l;if(!td){h={};for(var m in qd)h[qd[m]]=m;td=h}g=td[g];break}e.push({keyCode:g,ad:f})}d=e}else{m=e;g=d;if(ga(e[d])){m=e[d];g=0}for(d=[];g<m.length;g+=2)d.push({keyCode:m[g],ad:m[g+1]})}return d}
rd.prototype.k=function(){rd.m.k.call(this);this.nb={};Nc(this.sa,"keydown",this.hb,false,this);Rb&&M&&N("1.8")&&Nc(this.sa,"keyup",this.Oc,false,this);if($b&&!M){Nc(this.sa,"keypress",this.Qc,false,this);Nc(this.sa,"keyup",this.Rc,false,this)}this.sa=null};rd.prototype.Oc=function(c){if(c.keyCode==224){this.$c=true;pd(function(){this.$c=false},400,this)}else{var d=c.metaKey||this.$c;if((c.keyCode==67||c.keyCode==88||c.keyCode==86)&&d){c.metaKey=d;this.hb(c)}}};
function xd(c,d){return $b&&!M&&d.ctrlKey&&d.altKey&&!d.shiftKey}rd.prototype.Qc=function(c){if(c.keyCode>32&&xd(this,c))this.Yc=true};rd.prototype.Rc=function(c){!this.Yc&&xd(this,c)&&this.hb(c)};function vd(c,d,e){var f=d.shift();f=f.keyCode&255|f.ad<<8;var h=c[f];if(h&&e&&(d.length==0||y(h)))throw Error("Keyboard shortcut conflicts with existing shortcut");if(d.length){h||(h=c[f]={});vd(h,d,e)}else c[f]=e}
function yd(c,d,e,f){e=e||0;if((f=(f||c.nb)[d[e]])&&!y(f)&&d.length-e>1)return yd(c,d,e+1,f);return f}
rd.prototype.hb=function(c){if(zd(this,c))if(c.type=="keydown"&&xd(this,c))this.Yc=false;else{var d=c.keyCode&255|((c.shiftKey?1:0)|(c.ctrlKey?2:0)|(c.altKey?4:0)|(c.metaKey?8:0))<<8,e,f,h=pa();if(this.ta.Ia.length&&h-this.ta.sd<=1500)e=yd(this,this.ta.Ia);else this.ta.Ia.length=0;e=e?e[d]:this.nb[d];if(!e){e=this.nb[d];this.ta.Ia=[]}if(e&&y(e))f=e;else if(e){this.ta.Ia.push(d);this.ta.sd=h;M&&c.preventDefault()}else this.ta.Ia.length=0;if(f){this.Vd&&c.preventDefault();this.Wd&&c.stopPropagation();
d=this.dispatchEvent(new Ad(ud.Fd,f,c.target));d&=this.dispatchEvent(new Ad(ud.Ed+f,f,c.target));d||c.preventDefault();this.ta.Ia.length=0}}};
function zd(c,d){var e=d.keyCode;if(e==16||e==17||e==18)return false;var f=d.target,h=f.tagName=="TEXTAREA"||f.tagName=="INPUT"||f.tagName=="BUTTON"||f.tagName=="SELECT",g=!h&&(f.isContentEditable||f.ownerDocument&&f.ownerDocument.designMode=="on");if(!h&&!g)return true;if(c.xe[e]||c.Ud)return true;if(g)return false;if(c.Ke&&(d.altKey||d.ctrlKey||d.metaKey))return true;if(f.tagName=="INPUT"&&(f.type=="text"||f.type=="password"))return e==13;if(f.tagName=="INPUT"||f.tagName=="BUTTON")return e!=32;
return false}function Ad(c,d,e){mc.call(this,c,e);this.identifier=d}z(Ad,mc);function Bd(c){this.Ea=c}z(Bd,lc);var Cd=new sc(0,100);function Dd(c,d,e,f,h,g){if(ga(e))for(var l=0;l<e.length;l++)Dd(c,d,e[l],f,h,g);else{d=Lc(d,e,f||c,h||false,g||c.Ea||c);if(c.j)c.j[d]=true;else if(c.ya){c.j=tc(Cd);c.j[c.ya]=true;c.ya=null;c.j[d]=true}else c.ya=d}return c}
function Ed(c,d,e,f,h,g){if(c.ya||c.j)if(ga(e))for(var l=0;l<e.length;l++)Ed(c,d,e[l],f,h,g);else{a:{f=f||c;g=g||c.Ea||c;h=!!(h||false);if(d=Oc(d,e,h))for(e=0;e<d.length;e++)if(d[e].Va==f&&d[e].capture==h&&d[e].wb==g){d=d[e];break a}d=null}if(d){d=d.key;Pc(d);if(c.j)hb(c.j,d);else if(c.ya==d)c.ya=null}}return c}Bd.prototype.Lb=function(){if(this.j){for(var c in this.j){Pc(c);delete this.j[c]}uc(Cd,this.j);this.j=null}else this.ya&&Pc(this.ya)};Bd.prototype.k=function(){Bd.m.k.call(this);this.Lb()};
Bd.prototype.handleEvent=function(){throw Error("EventHandler.handleEvent not implemented");};function Fd(c,d){this.width=c;this.height=d}a=Fd.prototype;a.K=function(){return new Fd(this.width,this.height)};a.toString=function(){return"("+this.width+" x "+this.height+")"};a.ceil=function(){this.width=Math.ceil(this.width);this.height=Math.ceil(this.height);return this};a.floor=function(){this.width=Math.floor(this.width);this.height=Math.floor(this.height);return this};a.round=function(){this.width=Math.round(this.width);this.height=Math.round(this.height);return this};
a.scale=function(c){this.width*=c;this.height*=c;return this};function I(c,d){this.x=c!==undefined?c:0;this.y=d!==undefined?d:0}I.prototype.K=function(){return new I(this.x,this.y)};I.prototype.toString=function(){return"("+this.x+", "+this.y+")"};function Gd(c,d){var e=c.x-d.x;c=c.y-d.y;return Math.sqrt(e*e+c*c)}function Hd(c,d){return new I(c.x-d.x,c.y-d.y)}function S(c,d){return new I(c.x+d.x,c.y+d.y)};function Id(c,d,e,f){this.top=c;this.right=d;this.bottom=e;this.left=f}function Jd(){for(var c=new Id(arguments[0].y,arguments[0].x,arguments[0].y,arguments[0].x),d=1;d<arguments.length;d++){var e=arguments[d];c.top=Math.min(c.top,e.y);c.right=Math.max(c.right,e.x);c.bottom=Math.max(c.bottom,e.y);c.left=Math.min(c.left,e.x)}return c}Id.prototype.K=function(){return new Id(this.top,this.right,this.bottom,this.left)};
Id.prototype.toString=function(){return"("+this.top+"t, "+this.right+"r, "+this.bottom+"b, "+this.left+"l)"};Id.prototype.expand=function(c,d,e,f){if(ka(c)){this.top-=c.top;this.right+=c.right;this.bottom+=c.bottom;this.left-=c.left}else{this.top-=c;this.right+=d;this.bottom+=e;this.left-=f}return this};function Kd(c,d,e,f){this.left=c;this.top=d;this.width=e;this.height=f}Kd.prototype.K=function(){return new Kd(this.left,this.top,this.width,this.height)};Kd.prototype.toString=function(){return"("+this.left+", "+this.top+" - "+this.width+"w x "+this.height+"h)"};Kd.prototype.fb=function(){return new Fd(this.width,this.height)};var Ld;function Md(c){var d;d=(d=c.className)&&typeof d.split=="function"?d.split(/\s+/):[];var e;e=Ua(arguments,1);for(var f=0,h=0;h<e.length;h++)if(!E(d,e[h])){d.push(e[h]);f++}e=f==e.length;c.className=d.join(" ");return e};var Nd=!L||N("9");L&&N("9");function Od(c){return c?new Pd(c.nodeType==9?c:c.ownerDocument||c.document):Ld||(Ld=new Pd)}
function Qd(c,d,e,f){c=f||c;d=d&&d!="*"?d.toUpperCase():"";if(c.querySelectorAll&&c.querySelector&&(!Wb||document.compatMode=="CSS1Compat"||N("528"))&&(d||e))return c.querySelectorAll(d+(e?"."+e:""));if(e&&c.getElementsByClassName){c=c.getElementsByClassName(e);if(d){f={};for(var h=0,g=0,l;l=c[g];g++)if(d==l.nodeName)f[h++]=l;f.length=h;return f}else return c}c=c.getElementsByTagName(d||"*");if(e){f={};for(g=h=0;l=c[g];g++){d=l.className;if(typeof d.split=="function"&&E(d.split(/\s+/),e))f[h++]=l}f.length=
h;return f}else return c}function Rd(c,d){eb(d,function(e,f){if(f=="style")c.style.cssText=e;else if(f=="class")c.className=e;else if(f=="for")c.htmlFor=e;else if(f in Sd)c.setAttribute(Sd[f],e);else c[f]=e})}var Sd={cellpadding:"cellPadding",cellspacing:"cellSpacing",colspan:"colSpan",rowspan:"rowSpan",valign:"vAlign",height:"height",width:"width",usemap:"useMap",frameborder:"frameBorder",type:"type"};function Td(){return Ud(document,arguments)}
function Ud(c,d){var e=d[0],f=d[1];if(!Nd&&f&&(f.name||f.type)){e=["<",e];f.name&&e.push(' name="',wa(f.name),'"');if(f.type){e.push(' type="',wa(f.type),'"');var h={};lb(h,f);f=h;delete f.type}e.push(">");e=e.join("")}e=c.createElement(e);if(f)if(y(f))e.className=f;else ga(f)?Md.apply(null,[e].concat(f)):Rd(e,f);d.length>2&&Vd(c,e,d,2);return e}
function Vd(c,d,e,f){function h(l){if(l)d.appendChild(y(l)?c.createTextNode(l):l)}for(f=f;f<e.length;f++){var g=e[f];ha(g)&&!(ka(g)&&g.nodeType>0)?C(Wd(g)?Ta(g):g,h):h(g)}}function Xd(c){for(var d;d=c.firstChild;)c.removeChild(d)}function hd(c){return c&&c.parentNode?c.parentNode.removeChild(c):null}function Wd(c){if(c&&typeof c.length=="number")if(ka(c))return typeof c.item=="function"||typeof c.item=="string";else if(ja(c))return typeof c.item=="function";return false}
function Pd(c){this.ba=c||t.document||document}a=Pd.prototype;a.e=function(c){return y(c)?this.ba.getElementById(c):c};a.U=function(){return Ud(this.ba,arguments)};a.createElement=function(c){return this.ba.createElement(c)};a.createTextNode=function(c){return this.ba.createTextNode(c)};a.appendChild=function(c,d){c.appendChild(d)};L||M&&N("1.9.3");function Yd(c,d,e){if(d instanceof Fd){e=d.height;d=d.width}else{if(e==undefined)throw Error("missing height argument");e=e}c.style.width=Zd(d,true);c.style.height=Zd(e,true)}function Zd(c,d){if(typeof c=="number")c=(d?Math.round(c):c)+"px";return c}
function $d(c){var d=Vb&&!N("10"),e;a:{e=c.nodeType==9?c:c.ownerDocument||c.document;if(e.defaultView&&e.defaultView.getComputedStyle)if(e=e.defaultView.getComputedStyle(c,"")){e=e.display;break a}e=null}if((e||(c.currentStyle?c.currentStyle.display:null)||c.style.display)!="none")return d?new Fd(c.offsetWidth||c.clientWidth,c.offsetHeight||c.clientHeight):new Fd(c.offsetWidth,c.offsetHeight);e=c.style;var f=e.display,h=e.visibility,g=e.position;e.visibility="hidden";e.position="absolute";e.display=
"inline";if(d){d=c.offsetWidth||c.clientWidth;c=c.offsetHeight||c.clientHeight}else{d=c.offsetWidth;c=c.offsetHeight}e.display=f;e.position=g;e.visibility=h;return new Fd(d,c)}function ae(c,d){d=Od(d);var e=null;if(L){e=d.ba.createStyleSheet();be(e,c)}else{var f=Qd(d.ba,"head",void 0,void 0)[0];if(!f){e=Qd(d.ba,"body",void 0,void 0)[0];f=d.U("head");e.parentNode.insertBefore(f,e)}e=d.U("style");be(e,c);d.appendChild(f,e)}return e}
function be(c,d){if(L)c.cssText=d;else c[Wb?"innerText":"innerHTML"]=d};function ce(){}(function(c){c.Nc=function(){return c.Fe||(c.Fe=new c)}})(ce);ce.prototype.Me=0;ce.Nc();function de(c){this.ca=c||Od();this.Se=ee}z(de,Vc);de.prototype.Ee=ce.Nc();var ee=null;a=de.prototype;a.ra=null;a.L=false;a.h=null;a.Se=null;a.Je=null;a.ha=null;a.r=null;a.sb=null;a.Ze=false;a.e=ca("h");a.pc=function(c){if(this.ha&&this.ha!=c)throw Error("Method not supported");de.m.pc.call(this,c)};a.U=function(){this.h=this.ca.createElement("div")};
a.q=function(c){if(this.L)throw Error("Component already rendered");this.h||this.U();c?c.insertBefore(this.h,null):this.ca.ba.body.appendChild(this.h);if(!this.ha||this.ha.L)this.xa()};a.xa=function(){this.L=true;this.r&&C(this.r,function(c){!c.L&&c.e()&&c.xa()},void 0)};a.eb=function(){this.r&&C(this.r,function(c){c.L&&c.eb()},void 0);this.vb&&this.vb.Lb();this.L=false};
a.k=function(){de.m.k.call(this);this.L&&this.eb();if(this.vb){this.vb.pa();delete this.vb}this.r&&C(this.r,function(c){c.pa()},void 0);!this.Ze&&this.h&&hd(this.h);this.ha=this.Je=this.h=this.sb=this.r=null};
a.removeChild=function(c,d){if(c){var e=y(c)?c:c.ra||(c.ra=":"+(c.Ee.Me++).toString(36));c=this.sb&&e?ib(this.sb,e)||null:null;if(e&&c){hb(this.sb,e);Qa(this.r,c);if(d){c.eb();c.h&&hd(c.h)}d=c;if(d==null)throw Error("Unable to set parent component");d.ha=null;de.m.pc.call(d,null)}}if(!c)throw Error("Child is not in parent component");return c};function fe(c){this.ca=c||Od();J.call(this)}z(fe,J);a=fe.prototype;a.ae="goog-buttonset";a.Ec=null;a.h=null;a.$d=null;a.u=function(c,d,e,f){J.prototype.u.call(this,c,d);if(e)this.Ec=c;if(f)this.$d=c;return this};a.q=function(){if(this.h){this.h.innerHTML="";var c=Od(this.h);ob(this,function(d,e){d=c.U("button",{name:e},d);if(e==this.Ec)d.className=this.ae+"-default";this.h.appendChild(d)},this)}};var ge=qa("OK"),he=qa("Cancel"),ie=qa("Yes"),je=qa("No"),ke=qa("Save"),le=qa("Continue");
(new fe).u("ok",ge,true,true);(new fe).u("ok",ge,true).u("cancel",he,false,true);(new fe).u("yes",ie,true).u("no",je,false,true);(new fe).u("yes",ie).u("no",je,true).u("cancel",he,false,true);(new fe).u("continue",le).u("save",ke).u("cancel",he,true,true);function me(c,d){this.source=c;this.target=d};function ne(c,d,e){this.l=c;this.c=new J(d!==undefined?d:{});e!==undefined&&this.c.La(e)}ne.prototype.n=Kb("specview.view.Renderer");function oe(c,d){var e=(new Kd(d.left,d.top,d.right-d.left,d.bottom-d.top)).fb(),f=e.width,h=c.l.fb();e.scale(e.width/e.height>h.width/h.height?h.width/e.width:h.height/e.height);c=c.Te*e.width/f;e=Math.max(d.top,d.bottom);return new G(c,0,0,-c,-Math.min(d.left,d.right)*c,e*c)}ne.prototype.setTransform=ba("transform");function T(c,d){ne.call(this,c,pe,d)}z(T,ne);
T.prototype.Sa=function(c,d,e){d||(d=this.c.f("highlight").color);e||(e=new gd);var f=Ya(Math.atan2(c.target.a.y-c.source.a.y,c.target.a.x-c.source.a.x)*180/Math.PI),h=Ya(f+90);f=Ya(f-90);h=F(h);f=F(f);var g=this.transform.p,l=this.c.f("highlight").radius*g;c=H(this.transform,[c.source.a,c.target.a]);g=S(new I(l*Math.cos(h),-l*Math.sin(h)),c[0]);var n=S(new I(l*Math.cos(h),-l*Math.sin(h)),c[1]);h=S(new I(l*Math.cos(f),-l*Math.sin(f)),c[0]);f=S(new I(l*Math.cos(f),-l*Math.sin(f)),c[1]);l=new U;l.moveTo(c[0].x,
c[0].y);l.lineTo(g.x,g.y);l.lineTo(n.x,n.y);l.lineTo(c[1].x,c[1].y);l.close();d=new qe(d,0.15);e.add(this.l.Ca(l,null,d));g=new U;g.moveTo(c[0].x,c[0].y);g.lineTo(h.x,h.y);g.lineTo(f.x,f.y);g.lineTo(c[1].x,c[1].y);g.close();e.add(this.l.Ca(g,null,d));return e};function re(c){c=new me(c.source.a,c.target.a);c=Hd(c.target,c.source);return Math.atan2(c.y,c.x)}function se(c){return c.B!="C"||c.$()==1}
var pe={bond:{stroke:{width:1.5,color:"black"},fill:{color:"black"},"width-ratio":6,"symbol-space":0.3,"triple-dist":0.15,"quad-dist":0.13},highlight:{radius:0.3,color:"blue"}};function te(c,d){T.call(this,c,te.Ba,d)}z(te,T);te.prototype.q=function(c,d){this.setTransform(d);d=new U;var e=bb(this.transform,[c.la()])[0];c=H(this.transform,[c.b[0].a])[0];c=Gd(e,c)*0.5;d.moveTo(e.x+c,e.y);d.arcTo(c,c,0,180);d.moveTo(e.x+c,e.y);d.arcTo(c,c,0,-180)};function ue(){this.ed=pa()}new ue;ue.prototype.u=ba("ed");ue.prototype.reset=function(){this.u(pa())};ue.prototype.f=ca("ed");function ve(c,d){T.call(this,c,ve.Ba,d)}z(ve,T);
ve.prototype.q=function(c,d,e){this.setTransform(d);var f=Math.round(Gd(c.source.a,c.target.a)*12);if(f<8)f=8;this.n.log(Eb,"# zigZags "+f,void 0);var h=this.c.f("bond").stroke.width/10,g=re(c),l=g+Math.PI/2;g=g-Math.PI/2;var n=[];n.push(c.source.a);this.n.log(Eb,"# coords "+n.length,void 0);for(var m=null,o=1/f,q=0,s=1;s<=f;s++){q+=o;m=s%2==0?new G(1,0,0,1,Math.cos(l)*h*q,Math.sin(l)*h*q):new G(1,0,0,1,Math.cos(g)*h*q,Math.sin(g)*h*q);m=H(m,[new I(((f-s)*c.source.a.x+c.target.a.x*s)/f,((f-s)*c.source.a.y+
c.target.a.y*s)/f)])[0];n.push(m)}c=H(d,n);e.moveTo(c[1].x,c[1].y);d=2;for(f=c.length-1;d<f;d++){e.lineTo(c[d].x,c[d].y);e.moveTo(c[d].x,c[d].y)}};function we(c,d){T.call(this,c,we.Ba,d)}z(we,T);
we.prototype.q=function(c,d,e){this.setTransform(d);var f=this.c.f("bond").stroke.width/10,h=re(c),g=h+Math.PI/2;h=h-Math.PI/2;g=bb(new G(1,0,0,1,Math.cos(g)*f,Math.sin(g)*f),[c.target.a])[0];f=bb(new G(1,0,0,1,Math.cos(h)*f,Math.sin(h)*f),[c.target.a])[0];if(c.target.B!="C"){h=3*Gd(g,c.source.a);g.x=(g.x*(h-1)+c.source.a.x)/h;g.y=(g.y*(h-1)+c.source.a.y)/h;f.x=(f.x*(h-1)+c.source.a.x)/h;f.y=(f.y*(h-1)+c.source.a.y)/h}c=H(d,[c.source.a,g,f]);e.moveTo(c[0].x,c[0].y);e.lineTo(c[1].x,c[1].y);e.lineTo(c[2].x,
c[2].y)};function xe(c,d){T.call(this,c,xe.Ba,d)}z(xe,T);
xe.prototype.q=function(c,d,e){this.setTransform(d);var f=this.c.f("bond").stroke.width;f=new ye(f,this.c.f("bond").stroke.color);var h=re(c),g=h+Math.PI/2;h=h-Math.PI/2;var l=this.c.f("bond")["triple-dist"];g=new G(1,0,0,1,Math.cos(g)*l,Math.sin(g)*l);h=new G(1,0,0,1,Math.cos(h)*l,Math.sin(h)*l);g=H(g,[c.source.a,c.target.a]);h=H(h,[c.source.a,c.target.a]);c=H(d,[c.source.a,c.target.a,g[0],g[1],h[0],h[1]]);e.moveTo(c[0].x,c[0].y);e.lineTo(c[1].x,c[1].y);e.moveTo(c[2].x,c[2].y);e.lineTo(c[3].x,c[3].y);
e.moveTo(c[4].x,c[4].y);e.lineTo(c[5].x,c[5].y);this.l.Ca(e,f,null)};function ze(c,d){T.call(this,c,ze.Ba,d)}z(ze,T);
ze.prototype.q=function(c,d,e){this.setTransform(d);var f=Ae(c),h=new Be(Hd(c.target.a,c.source.a).x,Hd(c.target.a,c.source.a).y);h.scale(1/this.c.f("bond")["width-ratio"]);var g=new Be(-h.y,h.x),l=h.K().normalize().scale(this.c.f("bond")["symbol-space"]);if(f){var n=S(c.source.a,g),m=new me(c.source.a,c.target.a);f=f.la();((m.target.x-m.source.x)*(f.y-m.source.y)-(f.x-m.source.x)*(m.target.y-m.source.y))*((m.target.x-m.source.x)*(n.y-m.source.y)-(n.x-m.source.x)*(m.target.y-m.source.y))>0||Ce(g);
n=S(c.source.a,g);m=S(c.target.a,g);f=c.source.a;g=c.target.a;if(se(c.source)){n=S(n,l);f=S(f,l)}else n=S(n,h);if(se(c.target)){m=Hd(m,l);g=Hd(g,l)}else m=Hd(m,h)}else{g.scale(0.5);h=g;if(Math.abs(h.x)>0.08){g=h.x/0.08;h.x/=g;h.y/=g}if(Math.abs(h.y)>0.08){g=h.y/0.08;h.x/=g;h.y/=g}g=h;n=S(c.source.a,g);m=S(c.target.a,g);f=Hd(c.source.a,g);g=Hd(c.target.a,g);if(se(c.source)){n=S(n,l);f=S(f,l)}if(se(c.target)){m=Hd(m,l);g=Hd(g,l)}}c=H(d,[n,m,f,g]);e.moveTo(c[0].x,c[0].y);e.lineTo(c[1].x,c[1].y);e.moveTo(c[2].x,
c[2].y);e.lineTo(c[3].x,c[3].y)};function Ae(c){return Na(De(c.Wa),function(d){return E(d.g,c)})};function Ee(c,d){T.call(this,c,Ee.Ba,d)}z(Ee,T);
Ee.prototype.q=function(c,d,e){this.setTransform(d);var f=this.c.f("bond").stroke.width;f=new ye(f,this.c.f("bond").stroke.color);var h=re(c),g=h+Math.PI/2,l=h-Math.PI/2,n=this.c.f("bond")["quad-dist"],m=new G(1,0,0,1,Math.cos(g)*n/3,Math.sin(g)*n/3);h=new G(1,0,0,1,Math.cos(l)*n/3,Math.sin(l)*n/3);g=new G(1,0,0,1,Math.cos(g)*n,Math.sin(g)*n);l=new G(1,0,0,1,Math.cos(l)*n,Math.sin(l)*n);m=H(m,[c.source.a,c.target.a]);h=H(h,[c.source.a,c.target.a]);g=H(g,[c.source.a,c.target.a]);c=H(l,[c.source.a,
c.target.a]);d=H(d,[m[0],m[1],h[0],h[1],g[0],g[1],c[0],c[1]]);e.moveTo(d[0].x,d[0].y);e.lineTo(d[1].x,d[1].y);e.moveTo(d[2].x,d[2].y);e.lineTo(d[3].x,d[3].y);e.moveTo(d[4].x,d[4].y);e.lineTo(d[5].x,d[5].y);e.moveTo(d[6].x,d[6].y);e.lineTo(d[7].x,d[7].y);this.l.Ca(e,f,null)};function Fe(c,d){T.call(this,c,Fe.Ba,d)}z(Fe,T);
Fe.prototype.q=function(c,d,e){this.setTransform(d);var f=this.c.f("bond").stroke.width/10,h=re(c),g=h+Math.PI/2;h=h-Math.PI/2;g=new G(1,0,0,1,Math.cos(g)*f,Math.sin(g)*f);f=new G(1,0,0,1,Math.cos(h)*f,Math.sin(h)*f);g=H(g,[c.source.a,c.target.a]);f=H(f,[c.source.a,c.target.a]);d=H(d,[g[0],g[1],f[0],f[1],c.source.a]);f=0;if(c.target.B!="C")f=1;for(c=0;c<7-f;c++){e.moveTo(((7-c)*d[4].x+c*d[1].x)/7,((7-c)*d[4].y+c*d[1].y)/7);e.lineTo(((7-c)*d[4].x+c*d[3].x)/7,((7-c)*d[4].y+c*d[3].y)/7)}};function P(c,d,e,f,h,g){this.B=c!==undefined?c:"C";this.a=new I(d!==undefined?d:0,e!==undefined?e:0);this.g=new qb;this.Q=f!==undefined?f:0;this.He=g!==undefined?g:0;this.Ma=h!==undefined?h:false;this.Vf=null;this.he=new Array(3)}v("specview.model.Atom",P,void 0);P.prototype.ue=ca("B");v("specview.model.Atom.prototype.getSymbol",P.prototype.ue,void 0);P.prototype.je=ca("Q");v("specview.model.Atom.prototype.getCharge",P.prototype.je,void 0);P.prototype.$=function(){return this.g.ub()};
P.prototype.Tc=function(){var c=id[this.B],d=this.g.V();d=Ma(d,function(f,h){return f+h.ga},0);var e=0;if(c)e=c-d+this.Q;return e};v("specview.model.Atom.prototype.hydrogenCount",P.prototype.Tc,void 0);function Ge(c){for(var d=c.g.V(),e=[],f=0,h=d.length;f<h;f++)e.push(He(d[f],c));return e}P.prototype.K=function(){return new P(this.B,this.a.x,this.a.y,this.Q,this.Ma,this.He)};P.prototype.toString=function(){return"specview.model.Atom ["+this.B+"] "+this.a.toString()};function Q(c,d,e,f,h,g){this.source=c;this.target=d;this.ga=e!==undefined?e:Ie;this.ua=f!==undefined?f:Je;this.Ma=h!==undefined?h:false;this.Wa=g!==undefined?g:null}v("specview.model.Bond",Q,void 0);function He(c,d){if(d===c.source)return c.target;if(d===c.target)return c.source;return null}Q.prototype.K=function(){return new Q(this.source,this.target,this.ga,this.ua,this.Ma,this.Wa)};var Ie=1,Je=10;
Q.prototype.toString=function(){var c=this.Wa?this.Wa.name:"no molecule";return"specview.model.Bond["+this.ga+", "+this.ua+"]  "+this.source.toString()+" -- "+this.target.toString()+" mol: "+c};function Be(c,d){this.x=Number(c)||0;this.y=Number(d)||0}z(Be,I);Be.prototype.K=function(){return new Be(this.x,this.y)};Be.prototype.scale=function(c){this.x*=c;this.y*=c;return this};function Ce(c){c.x=-c.x;c.y=-c.y;return c}Be.prototype.normalize=function(){return this.scale(1/Math.sqrt(this.x*this.x+this.y*this.y))};Be.prototype.add=function(c){this.x+=c.x;this.y+=c.y;return this};function Ke(c,d){T.call(this,c,Ke.Ba,d)}z(Ke,T);Ke.prototype.q=function(c,d,e){this.setTransform(d);var f=[c.source.a,c.target.a],h=new Be(Hd(f[1],f[0]).x,Hd(f[1],f[0]).y);h.normalize();h.scale(this.c.f("bond")["symbol-space"]);if(se(c.source))f[0]=S(f[0],h);if(se(c.target))f[1]=Hd(f[1],h);f=H(d,[f[0],f[1]]);e.moveTo(f[0].x,f[0].y);e.lineTo(f[1].x,f[1].y)};function Le(c,d){this.l=c;this.c=new J;d&&this.c.La(d)}Le.prototype.n=Kb("specview.view.BondRendererFactory");var Me=jb({qe:Ie,ke:2,ve:3,ne:4}),Ne=jb({pe:Je,se:11,oe:13,re:12});a=Le.prototype;a.f=function(c){return this[Me[c.ga]].apply(this,[c.ua])};a.qe=function(c){return this[Ne[c]].apply(this)};a.pe=function(){if(!this.nd)this.nd=new Ke(this.l,this.c);return this.nd};a.se=function(){if(!this.od)this.od=new we(this.l,this.c);return this.od};
a.oe=function(){if(!this.md)this.md=new Fe(this.l,this.c);return this.md};a.re=function(){if(!this.pd)this.pd=new ve(this.l,this.c);return this.pd};a.ke=function(){if(!this.Jc)this.Jc=new ze(this.l,this.c);return this.Jc};a.ve=function(){if(!this.vd)this.vd=new xe(this.l,this.c);return this.vd};a.ne=function(){if(!this.dd)this.dd=new Ee(this.l,this.c);return this.dd};function Oe(c,d){ne.call(this,c,Pe,d)}z(Oe,ne);
Oe.prototype.q=function(c,d,e){this.setTransform(d);e||(e=new gd);var f=this.c.f("atom"),h=this.c.f(c.B)?this.c.f(c.B).color:f.color,g=d.p;g=new Qe(g/1.8>12?15:g/1.8,f.fontName);f=new ye(f.stroke.width,"black");h=new qe(h);d=H(d,[c.a])[0];var l={text:"",Db:"center",ma:"",Ja:""};if(c.B!="C"||c.$()<1||c.Q||c.$()==1&&this.c.f("showTerminalCarbons")){var n=c.Tc();if(n==0)l.text=c.B;else{var m,o=c.g.ub();m=Re(c,0);if(o>1){for(var q=1;q<o;++q)m+=Re(c,q);m=m/o%360}m=m>350||m<=10?"E":m>10&&m<=80?"SE":m>80&&
m<=100?"S":m>100&&m<=170?"SW":m>170&&m<=190?"W":m>190&&m<=260?"NW":m>260&&m<=280?"N":"NE";o="center";if(m=="SW"||m=="W"||m=="NW"){o="right";if(n==1)l.text="H";l.text+=c.B}else{o="left";l.text=c.B+"H"}if(n>1)l.Ja=String(n)}if(c.Q)if(c.Q>1)l.ma+="+"+c.Q;else if(c.Q<-1)l.ma+=c.Q;else if(c.Q==-1)l.ma="-";else if(c.Q==1)l.ma="+"}else l.text="";l.Db=o;c=this.l;o=l.text.length*0.55*g.size;n=g.size;if(l.text){e.add(Se(c,l.text,d.x-o/2,d.y-n/2,o,n,l.Db,null,g,f,h));if(l.Db=="left"){if(l.Ja||l.ma){m=this.c.f("subscriptSize");
l.Ja&&e.add(Se(c,l.Ja,d.x+o*0.9,d.y,m,m,"center",null,g,f,h));l.ma&&e.add(Se(c,l.ma,d.x+o,d.y-n*0.8,m,m,"center",null,g,f,h))}}else if(l.Db=="right")if(l.Ja||l.ma){m=this.c.f("subscriptSize");if(l.Ja){e.add(Se(c,"H",d.x-o*3,d.y-n/2,o,n,"center",null,g,f,h));e.add(Se(c,l.Ja,d.x-o*1.8,d.y,m,m,"center",null,g,f,h))}l.ma&&e.add(Se(c,l.ma,d.x+o,d.y-n*0.8,m,m,"center",null,g,f,h))}}return e};
Oe.prototype.Sa=function(c,d,e){var f=this.c.f("atom");d||(d=this.c.f(c.B)?this.c.f(c.B).color:f.color);e||(e=new gd);d=new qe(d,0.3);if(this.fc==-1){atomConfig=this.c.f("atom");this.fc=atomConfig.highlight.radius*this.transform.p}f=this.fc;c=H(this.transform,[c.a])[0];this.n.info("draw circle");e.add(this.l.Yb(c.x,c.y,f,f,null,d,void 0));return e};Oe.prototype.fc=-1;
function Re(c,d){if(c.g.V().length==0)return 0;d=c.g.V()[d];var e=d.target.a,f=d.source.a,h=e.y-f.y;e=e.x-f.x;if(c==d.source){e=-e;h=-h}c=Math.atan2(h,e)*180/Math.PI;if(c<0)c=360+c;return c}Oe.prototype.n=Kb("specview.view.AtomRenderer");
var Pe={atom:{color:"#FF9999",diameter:0.05,highlight:{radius:0.3},stroke:{width:0.15},fontName:"Arial"},showTerminalCarbons:true,margin:20,subscriptSize:5,N:{color:"blue"},O:{color:"red"},S:{color:"yellow"},P:{color:"orange"},Cl:{color:"green"},F:{color:"green"},Br:{color:"DarkRed"},I:{color:"purple"},C:{color:"black"},R1:{color:"black"},R2:{color:"black"},H:{color:"white"}};function Te(c,d){ne.call(this,c,Ue,d);this.Te=0.9;this.Ub=new Le(c,this.c);this.Tb=new Oe(c,this.c);this.Yd=new te(c,this.c)}z(Te,ne);Te.prototype.n=Kb("specview.view.MoleculeRenderer");
Te.prototype.q=function(c,d){this.n.info("rendering");if(c.na)c.na.clear();else c.na=new gd;c.jc=true;var e=D(c.b,function(l){return l.a});e=Jd.apply(null,e);if(!d){var f=this.c.f("margin");d=oe(this,e.expand(f,f,f,f))}this.setTransform(d);H(this.transform,[new I((e.left+e.right)/2,(e.top+e.bottom)/2)]);e=new ye(this.c.f("bond").stroke.width,this.c.f("bond").stroke.color);f=new qe(this.c.f("bond").fill.color);var h=new U;C(c.g,function(l){this.Ub.f(l).q(l,d,h)},this);var g=this.Yd;C(De(c),function(l){La(l.g,
function(n){return n.Ma}).length==l.g.length&&this.na.add(g.q(l,d,h))});c.na.add(this.l.Ca(h,e,f));C(c.b,function(l){this.Tb.q(l,d,c.na)},this)};Te.prototype.Sa=function(c,d,e){d||(d=this.c.f("highlight").color);e||(e=new gd);C(c.g,function(f){this.Ub.f(f).Sa(f,d,e)},this);C(c.b,function(f){this.Tb.Sa(f,d,e)},this);return e};var Ue={bond:{stroke:{width:2,color:"black"},fill:{color:"black"}},highlight:{radius:0.3,color:"blue"}};function Ve(c,d,e,f){this.qb=c;this.rb=d;this.Ob=e;this.Qb=f}Ve.prototype.K=function(){return new Ve(this.qb,this.rb,this.Ob,this.Qb)};function We(c,d,e){this.cells={};this.Na=d?d:2;this.Ye=e?e:0.3;this.$a=this.Ya=1E5;this.Rb=this.Pb=-100000;d=0;for(e=c.length;d<e;d++){var f=c[d].la();if(f.x<this.Ya)this.Ya=f.x;if(f.x>this.Pb)this.Pb=f.x;if(f.y<this.$a)this.$a=f.y;if(f.y>this.Rb)this.Rb=f.y}this.Ya-=1;this.$a-=1;this.Pb+=1;this.Rb+=1;this.width=this.Pb-this.Ya;this.height=this.Rb-this.$a;this.xc=Math.ceil(this.width/this.Na);this.cf=Math.ceil(this.height/this.Na);C(c,function(h){var g=h.la(),l=Math.floor((g.x-this.Ya)/this.Na);g=
Math.floor((g.y-this.$a)/this.Na)*this.xc+l;this.cells[g]||(this.cells[g]=[]);this.cells[g].push(h)},this)}function Xe(c,d){var e=[],f=Math.floor((d.x-c.Ya)/c.Na);d=Math.floor((d.y-c.$a)/c.Na);var h=f-1;for(f=f+2;h<f;h++)if(!(h<0||h>=c.xc))for(var g=d-1,l=d+2;g<l;g++)g<0||g>=c.cf||e.push(g*c.xc+h);return e}
function Ye(c,d){var e=[],f=Xe(c,d);i=0;for(li=f.length;i<li;i++){var h=c.cells[f[i]];if(h){j=0;for(lj=h.length;j<lj;j++){var g=h[j],l=g.cc(d);l<c.Ye&&e.push({kb:g.kb,Ic:l})}}}e.sort(function(n,m){return n.Ic-m.Ic});return D(e,function(n){return n.kb})}
function Ze(c){var d=D(c,function(e){return{kb:e,la:function(){return e.la()},cc:function(f){return Gd(e.la(),f)/4}}});C(c,function(e){d=Sa(d,D(e.b,function(f){return{kb:f,la:function(){return f.a},cc:function(h){return Gd(f.a,h)}}}));d=Sa(d,D(e.g,function(f){return{kb:f,la:function(){return(new Be(S(f.source.a,f.target.a).x,S(f.source.a,f.target.a).y)).scale(0.5)},cc:function(h){var g=new Ve(f.source.a.x,f.source.a.y,f.target.a.x,f.target.a.y),l;l=h.x;var n;if(l instanceof I){n=l.y;l=l.x}else n=
h.y;var m=g.qb,o=g.rb,q=g.Ob-g.qb,s=g.Qb-g.rb;l=((l-m)*(g.Ob-m)+(n-o)*(g.Qb-o))/(q*q+s*s);return Gd(new I(g.qb+Math.min(Math.max(l,0),1)*(g.Ob-g.qb),g.rb+Math.min(Math.max(l,0),1)*(g.Qb-g.rb)),h)}}}))});return d};var $e,af,bf,cf,df,ef,ff;ff=ef=df=cf=bf=af=$e=false;var gf=Sb();if(gf)if(gf.indexOf("Firefox")!=-1)$e=true;else if(gf.indexOf("Camino")!=-1)af=true;else if(gf.indexOf("iPhone")!=-1||gf.indexOf("iPod")!=-1)bf=true;else if(gf.indexOf("iPad")!=-1)cf=true;else if(gf.indexOf("Android")!=-1)df=true;else if(gf.indexOf("Chrome")!=-1)ef=true;else if(gf.indexOf("Safari")!=-1)ff=true;var hf=af,jf=bf,kf=cf,lf=df,mf=ef,nf=ff;var of;a:{var pf="",qf,rf;if($e)qf=/Firefox\/([0-9.]+)/;else if(L||Vb){of=ac;break a}else if(mf)qf=/Chrome\/([0-9.]+)/;else if(nf)qf=/Safari\/([0-9.]+)/;else if(jf||kf){qf=/Version\/(\S+).*Mobile\/(\S+)/;rf=true}else if(lf)qf=/Android\s+([0-9.]+)(?:.*Version\/([0-9.]+))?/;else if(hf)qf=/Camino\/([0-9.]+)/;if(qf){var sf=qf.exec(Sb());pf=sf?rf?sf[1]+"."+sf[2]:sf[2]||sf[1]:""}of=pf};L&&N("7.0");M&&N("1.8");L||Vb||M&&N("1.9");L||Wb&&N("525");Wb&&N("531");Wb&&N("528");M&&N("1.9")||L||Vb||Wb&&N("531");M||Wb&&N("526");mf&&Da(of,"4")>=0||nf&&Da(of,"533");function R(c,d){this.h=c;this.fa=d;this.Wb=false}z(R,Vc);a=R.prototype;a.fa=null;a.h=null;a.ud=null;a.e=ca("h");a.addEventListener=function(c,d,e,f){Lc(this.h,c,d,e,f)};a.removeEventListener=function(c,d,e,f){Nc(this.h,c,d,e,f)};a.k=function(){R.m.k.call(this);Rc(this.h)};function V(c,d,e,f){R.call(this,c,d);this.kd(e);this.hd(f)}z(V,R);a=V.prototype;a.fill=null;a.sc=null;a.hd=function(c){this.fill=c;this.fa.nc(this,c)};a.le=ca("fill");a.kd=function(c){this.sc=c;this.fa.oc(this,c)};a.te=ca("sc");function tf(c,d,e,f){V.call(this,c,d,e,f)}z(tf,V);function uf(c,d,e,f){V.call(this,c,d,e,f)}z(uf,V);function vf(c,d){R.call(this,c,d)}z(vf,R);function wf(c,d,e,f){V.call(this,c,d,e,f)}z(wf,V);function xf(c,d,e,f){V.call(this,c,d,e,f)}z(xf,V);function yf(c,d){R.call(this,c,d)}z(yf,R);function zf(c,d){R.call(this,c,d)}z(zf,vf);zf.prototype.clear=function(){Xd(this.e())};function Af(c,d,e,f){V.call(this,c,d,e,f)}z(Af,xf);function Bf(c,d,e,f){V.call(this,c,d,e,f)}z(Bf,tf);function Cf(c,d,e,f){V.call(this,c,d,e,f)}z(Cf,uf);Cf.prototype.qc=function(c){Df(this.fa,this.e(),{d:Ef(c)})};function Ff(c,d,e,f){V.call(this,c,d,e,f)}z(Ff,wf);function Gf(c,d){R.call(this,c,d)}z(Gf,yf);function Qe(c,d){this.size=c;this.bc=d}Qe.prototype.bold=false;Qe.prototype.gc=false;function Hf(){};function qe(c,d){this.T=c;this.lb=d||1}z(qe,Hf);function ye(c,d){this.wc=c;this.T=d};function U(){this.t=[];this.i=[];this.Z=[]}U.prototype.ja=null;U.prototype.z=null;U.prototype.Ha=true;var If=[];If[0]=2;If[1]=2;If[2]=6;If[3]=6;If[4]=0;a=U.prototype;a.clear=function(){this.t.length=0;this.i.length=0;this.Z.length=0;delete this.ja;delete this.z;delete this.Ha;return this};a.moveTo=function(c,d){if(this.t[this.t.length-1]==0)this.Z.length-=2;else{this.t.push(0);this.i.push(1)}this.Z.push(c,d);this.z=this.ja=[c,d];return this};
a.lineTo=function(){var c=this.t[this.t.length-1];if(c==null)throw Error("Path cannot start with lineTo");if(c!=1){this.t.push(1);this.i.push(0)}for(c=0;c<arguments.length;c+=2){var d=arguments[c],e=arguments[c+1];this.Z.push(d,e)}this.i[this.i.length-1]+=c/2;this.z=[d,e];return this};
a.Dc=function(){var c=this.t[this.t.length-1];if(c==null)throw Error("Path cannot start with curve");if(c!=2){this.t.push(2);this.i.push(0)}for(c=0;c<arguments.length;c+=6){var d=arguments[c+4],e=arguments[c+5];this.Z.push(arguments[c],arguments[c+1],arguments[c+2],arguments[c+3],d,e)}this.i[this.i.length-1]+=c/6;this.z=[d,e];return this};a.close=function(){var c=this.t[this.t.length-1];if(c==null)throw Error("Path cannot start with close");if(c!=4){this.t.push(4);this.i.push(1);this.z=this.ja}return this};
a.arcTo=function(c,d,e,f){var h=this.z[0]-c*Math.cos(F(e)),g=this.z[1]-d*Math.sin(F(e));h=h+c*Math.cos(F(e+f));g=g+d*Math.sin(F(e+f));this.t.push(3);this.i.push(1);this.Z.push(c,d,e,f,h,g);this.Ha=false;this.z=[h,g];return this};
a.Xd=function(c,d,e,f){var h=this.z[0]-c*Math.cos(F(e)),g=this.z[1]-d*Math.sin(F(e)),l=F(f);f=Math.ceil(Math.abs(l)/Math.PI*2);l=l/f;e=F(e);for(var n=0;n<f;n++){var m=Math.cos(e),o=Math.sin(e),q=4/3*Math.sin(l/2)/(1+Math.cos(l/2)),s=h+(m-q*o)*c,u=g+(o+q*m)*d;e+=l;m=Math.cos(e);o=Math.sin(e);this.Dc(s,u,h+(m+q*o)*c,g+(o-q*m)*d,h+m*c,g+o*d)}return this};function Jf(c,d){for(var e=c.Z,f=0,h=0,g=c.t.length;h<g;h++){var l=c.t[h],n=If[l]*c.i[h];d(l,e.slice(f,f+n));f+=n}}
U.prototype.K=function(){var c=new this.constructor;c.t=this.t.concat();c.i=this.i.concat();c.Z=this.Z.concat();c.ja=this.ja&&this.ja.concat();c.z=this.z&&this.z.concat();c.Ha=this.Ha;return c};var Kf={};Kf[0]=U.prototype.moveTo;Kf[1]=U.prototype.lineTo;Kf[4]=U.prototype.close;Kf[2]=U.prototype.Dc;Kf[3]=U.prototype.Xd;function Lf(c){if(c.Ha)return c.K();var d=new U;Jf(c,function(e,f){Kf[e].apply(d,f)});return d}
U.prototype.transform=function(c){if(!this.Ha)throw Error("Non-simple path");c.transform(this.Z,0,this.Z,0,this.Z.length/2);this.ja&&c.transform(this.ja,0,this.ja,0,1);this.z&&this.ja!=this.z&&c.transform(this.z,0,this.z,0,1);return this};function Mf(c,d,e,f,h){de.call(this,h);this.width=c;this.height=d;this.aa=e||null;this.db=f||null}z(Mf,de);Mf.prototype.w=null;Mf.prototype.wa=0;Mf.prototype.Aa=0;function Nf(c){return c.aa?new Fd(c.aa,c.db):c.R()}Mf.prototype.fb=function(){return this.R()};Mf.prototype.R=function(){if(this.L)return $d(this.e());if(ia(this.width)&&ia(this.height))return new Fd(this.width,this.height);return null};function Of(c){var d=c.R();return d?d.width/Nf(c).width:0}
function Se(c,d,e,f,h,g,l,n,m,o,q,s){var u=m.size/2;f=n=="bottom"?f+g-u:n=="center"?f+g/2:f+u;return c.$b(d,e,f,e+h,f,l,m,o,q,s)};function Pf(c,d,e,f,h){Mf.call(this,c,d,e,f,h);this.Fc={};this.uc=Wb&&!N(526);this.Ea=new Bd(this)}var Qf;z(Pf,Mf);function Rf(c,d,e){d=c.ca.ba.createElementNS("http://www.w3.org/2000/svg",d);e&&Df(c,d,e);return d}function Df(c,d,e){for(var f in e)d.setAttribute(f,e[f])}a=Pf.prototype;a.v=function(c,d){(d||this.w).e().appendChild(c.e())};a.nc=function(c,d){c=c.e();if(d instanceof qe){c.setAttribute("fill",d.T);c.setAttribute("fill-opacity",d.lb)}else c.setAttribute("fill","none")};
a.oc=function(c,d){c=c.e();if(d){c.setAttribute("stroke",d.T);d=d.wc;y(d)&&d.indexOf("px")!=-1?c.setAttribute("stroke-width",parseFloat(d)/Of(this)):c.setAttribute("stroke-width",d)}else c.setAttribute("stroke","none")};
a.U=function(){var c=Rf(this,"svg",{width:this.width,height:this.height,overflow:"hidden"}),d=Rf(this,"g");this.Xb=Rf(this,"defs");this.w=new zf(d,this);c.appendChild(this.Xb);c.appendChild(d);this.h=c;if(this.aa||this.wa||this.Aa){this.e().setAttribute("preserveAspectRatio","none");this.uc?this.Nb():this.e().setAttribute("viewBox",this.wa+" "+this.Aa+" "+(this.aa?this.aa+" "+this.db:""))}};
a.Nb=function(){if(this.L&&(this.aa||this.wa||!this.Aa)){var c=this.R();if(c.width==0)this.e().style.visibility="hidden";else{this.e().style.visibility="";var d=-this.wa,e=-this.Aa,f=c.width/this.aa;c=c.height/this.db;this.w.e().setAttribute("transform","scale("+f+" "+c+") translate("+d+" "+e+")")}}};
a.R=function(){if(!M)return this.L?$d(this.e()):Pf.m.R.call(this);var c=this.width,d=this.height,e=y(c)&&c.indexOf("%")!=-1,f=y(d)&&d.indexOf("%")!=-1;if(!this.L&&(e||f))return null;var h,g;if(e){h=this.e().parentNode;g=$d(h);c=parseFloat(c)*g.width/100}if(f){h=h||this.e().parentNode;g=g||$d(h);d=parseFloat(d)*g.height/100}return new Fd(c,d)};a.clear=function(){this.w.clear();Xd(this.Xb);this.Fc={}};
a.Yb=function(c,d,e,f,h,g,l){c=Rf(this,"ellipse",{cx:c,cy:d,rx:e,ry:f});h=new Af(c,this,h,g);this.v(h,l);return h};a.Zb=function(c,d,e,f,h,g,l){c=Rf(this,"rect",{x:c,y:d,width:e,height:f});h=new Bf(c,this,h,g);this.v(h,l);return h};a.drawImage=function(c,d,e,f,h,g){c=Rf(this,"image",{x:c,y:d,width:e,height:f,"image-rendering":"optimizeQuality",preserveAspectRatio:"none"});c.setAttributeNS("http://www.w3.org/1999/xlink","href",h);h=new Gf(c,this);this.v(h,g);return h};
a.$b=function(c,d,e,f,h,g,l,n,m,o){var q=Math.round(Ya(Math.atan2(h-e,f-d)*180/Math.PI));f=f-d;h=h-e;h=Math.round(Math.sqrt(f*f+h*h));var s=l.size;f={"font-family":l.bc,"font-size":s};var u=Math.round(s*0.85);s=Math.round(e-s/2+u);u=d;if(g=="center"){u+=Math.round(h/2);f["text-anchor"]="middle"}else if(g=="right"){u+=h;f["text-anchor"]="end"}f.x=u;f.y=s;if(l.bold)f["font-weight"]="bold";if(l.gc)f["font-style"]="italic";if(q!=0)f.transform="rotate("+q+" "+d+" "+e+")";d=Rf(this,"text",f);d.appendChild(this.ca.ba.createTextNode(c));
if(n==null&&M&&Rb){c="black";if(m instanceof qe)c=m.T;n=new ye(1,c)}m=new Ff(d,this,n,m);this.v(m,o);return m};a.Ca=function(c,d,e,f){c=Rf(this,"path",{d:Ef(c)});d=new Cf(c,this,d,e);this.v(d,f);return d};
function Ef(c){var d=[];Jf(c,function(e,f){switch(e){case 0:d.push("M");Array.prototype.push.apply(d,f);break;case 1:d.push("L");Array.prototype.push.apply(d,f);break;case 2:d.push("C");Array.prototype.push.apply(d,f);break;case 3:e=f[3];d.push("A",f[0],f[1],0,Math.abs(e)>180?1:0,e>0?1:0,f[4],f[5]);break;case 4:d.push("Z");break}});return d.join(" ")}
Pf.prototype.xa=function(){var c=this.R();Pf.m.xa.call(this);c||this.dispatchEvent("resize");if(this.uc){c=this.width;var d=this.height;typeof c=="string"&&c.indexOf("%")!=-1&&typeof d=="string"&&d.indexOf("%")!=-1&&Dd(this.Ea,Sf(),od,this.Nb);this.Nb()}};Pf.prototype.eb=function(){Pf.m.eb.call(this);this.uc&&Ed(this.Ea,Sf(),od,this.Nb)};Pf.prototype.k=function(){delete this.Fc;delete this.Xb;delete this.w;Pf.m.k.call(this)};function Sf(){if(!Qf){Qf=new md(400);Qf.start()}return Qf};function Tf(){return this.h=this.fa.ca.e(this.ra)||this.h}function Uf(c,d){this.ra=c.id;R.call(this,c,d)}z(Uf,vf);Uf.prototype.e=Tf;Uf.prototype.clear=function(){Xd(this.e())};function Vf(c,d,e,f,h,g,l,n){this.ra=c.id;V.call(this,c,d,l,n);this.nf=e;this.of=f;this.cg=h;this.dg=g}z(Vf,xf);Vf.prototype.e=Tf;function Wf(c,d,e,f){this.ra=c.id;V.call(this,c,d,e,f)}z(Wf,tf);Wf.prototype.e=Tf;function Xf(c,d,e,f){this.ra=c.id;V.call(this,c,d,e,f)}z(Xf,uf);Xf.prototype.e=Tf;
Xf.prototype.qc=function(c){Yf(this.e(),"path",Zf(c))};function $f(c,d,e,f){this.ra=c.id;V.call(this,c,d,e,f)}z($f,wf);$f.prototype.e=Tf;function ag(c,d){this.ra=c.id;R.call(this,c,d)}z(ag,yf);ag.prototype.e=Tf;function bg(c,d,e,f,h){Mf.call(this,c,d,e,f,h);this.Ea=new Bd(this)}z(bg,Mf);var cg=document.documentMode&&document.documentMode>=8;function dg(c){return y(c)&&ua(c,"%")?c:parseFloat(c.toString())+"px"}function eg(c){return Math.round((parseFloat(c.toString())-0.5)*100)}function W(c){return Math.round(parseFloat(c.toString())*100)}function Yf(c,d,e){if(cg)c[d]=e;else c.setAttribute(d,e)}function fg(c,d){c=c.ca.createElement("g_vml_:"+d);c.id="goog_"+Fa++;return c}
function gg(c){if(cg&&c.L)c.e().innerHTML=c.e().innerHTML}bg.prototype.v=function(c,d){(d||this.w).e().appendChild(c.e());gg(this)};
bg.prototype.nc=function(c,d){c=c.e();c.fillcolor="";for(var e=0;e<c.childNodes.length;e++){var f=c.childNodes[e];f.tagName=="fill"&&c.removeChild(f)}if(d instanceof qe)if(d.T=="transparent")c.filled=false;else if(d.lb!=1){c.filled=true;e=fg(this,"fill");e.opacity=Math.round(d.lb*100)+"%";e.color=d.T;c.appendChild(e)}else{c.filled=true;c.fillcolor=d.T}else c.filled=false;gg(this)};
bg.prototype.oc=function(c,d){c=c.e();if(d){c.stroked=true;var e=d.wc;if(y(e)&&e.indexOf("px")==-1)e=parseFloat(e);else e*=Of(this);var f=c.getElementsByTagName("stroke")[0];if(e<1){f=f||fg(this,"stroke");f.opacity=e;f.gg="1px";f.color=d.T;c.appendChild(f)}else{f&&c.removeChild(f);c.strokecolor=d.T;c.strokeweight=e+"px"}}else c.stroked=false;gg(this)};
function hg(c,d,e,f,h){var g=c.style;g.position="absolute";g.left=eg(d)+"px";g.top=eg(e)+"px";g.width=W(f)+"px";g.height=W(h)+"px";if(c.tagName=="shape")c.coordsize=W(f)+" "+W(h)}function ig(c,d){d=fg(c,d);c=Nf(c);hg(d,0,0,c.width,c.height);return d}try{eval("document.namespaces")}catch(jg){}a=bg.prototype;
a.U=function(){var c=this.ca.ba;if(!c.namespaces.g_vml_){cg?c.namespaces.add("g_vml_","urn:schemas-microsoft-com:vml","#default#VML"):c.namespaces.add("g_vml_","urn:schemas-microsoft-com:vml");c.createStyleSheet().cssText="g_vml_\\:*{behavior:url(#default#VML)}"}c=this.width;var d=this.height,e=this.ca.U("div",{style:"overflow:hidden;position:relative;width:"+dg(c)+";height:"+dg(d)});this.h=e;var f=fg(this,"group"),h=f.style;h.position="absolute";h.left=h.top=0;h.width=this.width;h.height=this.height;
f.coordsize=this.aa?W(this.aa)+" "+W(this.db):W(c)+" "+W(d);f.coordorigin=this.wa!==undefined?W(this.wa)+" "+W(this.Aa):"0 0";e.appendChild(f);this.w=new Uf(f,this);Lc(e,"resize",oa(this.ec,this))};a.ec=function(){var c=$d(this.e()),d=this.w.e().style;if(c.width){d.width=c.width+"px";d.height=c.height+"px"}else{for(c=this.e();c&&c.currentStyle&&c.currentStyle.display!="none";)c=c.parentNode;c&&c.currentStyle&&Dd(this.Ea,c,"propertychange",this.ec)}this.dispatchEvent("resize")};
a.R=function(){var c=this.e();return new Fd(c.style.pixelWidth||c.offsetWidth||1,c.style.pixelHeight||c.offsetHeight||1)};a.clear=function(){this.w.clear()};a.Yb=function(c,d,e,f,h,g,l){var n=fg(this,"oval");hg(n,c-e,d-f,e*2,f*2);c=new Vf(n,this,c,d,e,f,h,g);this.v(c,l);return c};a.Zb=function(c,d,e,f,h,g,l){var n=fg(this,"rect");hg(n,c,d,e,f);c=new Wf(n,this,h,g);this.v(c,l);return c};
a.drawImage=function(c,d,e,f,h,g){var l=fg(this,"image");hg(l,c,d,e,f);Yf(l,"src",h);c=new ag(l,this);this.v(c,g);return c};
a.$b=function(c,d,e,f,h,g,l,n,m,o){var q=ig(this,"shape"),s=fg(this,"path");d="M"+eg(d)+","+eg(e)+"L"+eg(f)+","+eg(h)+"E";Yf(s,"v",d);Yf(s,"textpathok","true");d=fg(this,"textpath");d.setAttribute("on","true");e=d.style;e.fontSize=l.size*Of(this);e.fontFamily=l.bc;if(g!=null)e["v-text-align"]=g;if(l.bold)e.fontWeight="bold";if(l.gc)e.fontStyle="italic";Yf(d,"string",c);q.appendChild(s);q.appendChild(d);c=new $f(q,this,n,m);this.v(c,o);return c};
a.Ca=function(c,d,e,f){var h=ig(this,"shape");Yf(h,"path",Zf(c));c=new Xf(h,this,d,e);this.v(c,f);return c};
function Zf(c){var d=[];Jf(c,function(e,f){switch(e){case 0:d.push("m");Array.prototype.push.apply(d,D(f,W));break;case 1:d.push("l");Array.prototype.push.apply(d,D(f,W));break;case 2:d.push("c");Array.prototype.push.apply(d,D(f,W));break;case 4:d.push("x");break;case 3:var h=f[2]+f[3];e=W(f[4]-f[0]*Math.cos(F(h)));h=W(f[5]-f[1]*Math.sin(F(h)));var g=W(f[0]),l=W(f[1]),n=Math.round(f[2]*-65536);f=Math.round(f[3]*-65536);d.push("ae",e,h,g,l,n,f);break}});return d.join(" ")}
bg.prototype.xa=function(){bg.m.xa.call(this);this.ec();gg(this)};bg.prototype.k=function(){this.w=null;bg.m.k.call(this)};function kg(c){R.call(this,null,c);this.r=[]}z(kg,vf);kg.prototype.clear=function(){if(this.r.length){this.r.length=0;lg(this.fa)}};kg.prototype.appendChild=function(c){this.r.push(c)};kg.prototype.da=function(){for(var c=0,d=this.r.length;c<d;c++)mg(this.fa,this.r[c])};
function ng(c,d,e,f,h,g,l,n){V.call(this,c,d,l,n);this.de=e;this.ee=f;this.fd=h;this.gd=g;this.Fa=new U;this.Fa.clear();this.Fa.moveTo(this.de+this.fd*Math.cos(F(0)),this.ee+this.gd*Math.sin(F(0)));this.Fa.arcTo(this.fd,this.gd,0,360);this.Fa.close();this.Ne=new og(null,d,this.Fa,l,n)}z(ng,xf);ng.prototype.da=function(c){this.Ne.da(c)};function pg(c,d,e,f,h,g,l,n){V.call(this,c,d,l,n);this.Za=e;this.ab=f;this.pb=h;this.gb=g}z(pg,tf);pg.prototype.Pa=false;
pg.prototype.da=function(c){this.Pa=true;c.beginPath();c.moveTo(this.Za,this.ab);c.lineTo(this.Za,this.ab+this.gb);c.lineTo(this.Za+this.pb,this.ab+this.gb);c.lineTo(this.Za+this.pb,this.ab);c.closePath()};function og(c,d,e,f,h){V.call(this,c,d,f,h);this.qc(e)}z(og,uf);og.prototype.Pa=false;og.prototype.qc=function(c){this.Fa=c.Ha?c:Lf(c);this.Pa&&lg(this.fa)};
og.prototype.da=function(c){this.Pa=true;c.beginPath();Jf(this.Fa,function(d,e){switch(d){case 0:c.moveTo(e[0],e[1]);break;case 1:for(d=0;d<e.length;d+=2)c.lineTo(e[d],e[d+1]);break;case 2:for(d=0;d<e.length;d+=6)c.bezierCurveTo(e[d],e[d+1],e[d+2],e[d+3],e[d+4],e[d+5]);break;case 3:throw Error("Canvas paths cannot contain arcs");case 4:c.closePath();break}})};
function qg(c,d,e,f,h,g,l,n,m,o){V.call(this,null,c,m,o);this.rd=d;this.wd=e;this.af=f;this.xd=h;this.bf=g;this.Td=l||"left";this.ie=n;this.h=Td("DIV",{style:"display:table;position:absolute;padding:0;margin:0;border:0"});this.Ab=Td("DIV",{style:"display:table-cell;padding: 0;margin: 0;border: 0"});e=this.wd;n=this.xd;f=this.af;h=this.bf;m=this.Td;g=this.ie;d=this.h.style;l=Of(this.fa);o=this.fa;var q=o.R();o=q?q.height/Nf(o).height:0;if(e==n){d.lineHeight="90%";this.Ab.style.verticalAlign=m=="center"?
"middle":m=="left"?f<h?"top":"bottom":f<h?"bottom":"top";d.textAlign="center";n=g.size*l;d.top=Math.round(Math.min(f,h)*o)+"px";d.left=Math.round((e-n/2)*l)+"px";d.width=Math.round(n)+"px";d.height=Math.abs(f-h)*o+"px";d.fontSize=g.size*0.6*o+"pt"}else{d.lineHeight="100%";this.Ab.style.verticalAlign="top";d.textAlign=m;d.top=Math.round(((f+h)/2-g.size*2/3)*o)+"px";d.left=Math.round(e*l)+"px";d.width=Math.round(Math.abs(n-e)*l)+"px";d.height="auto";d.fontSize=g.size*o+"pt"}d.fontWeight=g.bold?"bold":
"normal";d.fontStyle=g.gc?"italic":"normal";d.fontFamily=g.bc;e=this.fill;d.color=e.T||e.Mc();this.Ab.innerHTML=this.wd==this.xd?D(this.rd.split(""),wa).join("<br>"):wa(this.rd);c.e().appendChild(this.h);this.h.appendChild(this.Ab)}z(qg,wf);qg.prototype.hd=function(c){this.fill=c;if(this.h)this.h.style.color=c.T||c.Mc()};qg.prototype.kd=function(){};qg.prototype.da=function(){};function rg(c,d,e,f,h,g,l){R.call(this,c,d);this.Za=e;this.ab=f;this.pb=h;this.gb=g;this.We=l}z(rg,yf);rg.prototype.Pa=false;
rg.prototype.da=function(c){if(this.Uc){this.pb&&this.gb&&c.drawImage(this.Uc,this.Za,this.ab,this.pb,this.gb);this.Pa=true}else{c=new Image;c.onload=oa(this.ye,this,c);c.src=this.We}};rg.prototype.ye=function(c){this.Uc=c;lg(this.fa)};function sg(c,d,e,f,h){Mf.call(this,c,d,e,f,h)}z(sg,Mf);sg.prototype.nc=function(){lg(this)};sg.prototype.oc=function(){lg(this)};function tg(c,d){c=c.getContext();c.save();d=d.ud?d.ud.K():new Za;var e=d.W,f=d.X;if(e||f)c.translate(e,f);(d=d.A)&&c.rotate(Math.asin(d))}sg.prototype.U=function(){var c=this.ca.U("div",{style:"position:relative;overflow:hidden"});this.h=c;this.cb=this.ca.U("canvas");c.appendChild(this.cb);this.Ie=this.w=new kg(this);this.Pe=0;ug(this)};
sg.prototype.getContext=function(){this.e()||this.U();if(!this.Oa){this.Oa=this.cb.getContext("2d");this.Oa.save()}return this.Oa};sg.prototype.R=function(){var c=this.width,d=this.height,e=y(c)&&c.indexOf("%")!=-1,f=y(d)&&d.indexOf("%")!=-1;if(!this.L&&(e||f))return null;var h,g;if(e){h=this.e().parentNode;g=$d(h);c=parseFloat(c)*g.width/100}if(f){h=h||this.e().parentNode;g=g||$d(h);d=parseFloat(d)*g.height/100}return new Fd(c,d)};
function ug(c){Yd(c.e(),c.width,c.height);var d=c.R();if(d){Yd(c.cb,d.width,d.height);c.cb.width=d.width;c.cb.height=d.height;c.Oa=null}}sg.prototype.reset=function(){var c=this.getContext();c.restore();var d=this.R();d.width&&d.height&&c.clearRect(0,0,d.width,d.height);c.save()};sg.prototype.clear=function(){this.reset();this.w.clear();for(var c=this.e();c.childNodes.length>1;)c.removeChild(c.lastChild)};
function lg(c){if(c.bg)c.$f=true;else if(c.L){c.reset();if(c.aa){var d=c.R();c.getContext().scale(d.width/c.aa,d.height/c.db)}if(c.wa||c.Aa)c.getContext().translate(-c.wa,-c.Aa);tg(c,c.w);c.w.da(c.Oa);c.getContext().restore()}}
function mg(c,d){if(!(d instanceof qg)){var e=c.getContext();tg(c,d);if(!d.le||!d.te)d.da(e);else{var f=d.fill;if(f)if(f instanceof qe){if(f.lb!=0){e.globalAlpha=f.lb;e.fillStyle=f.T;d.da(e);e.fill();e.globalAlpha=1}}else{var h=e.createLinearGradient(f.sf(),f.uf(),f.tf(),f.vf());h.addColorStop(0,f.Mc());h.addColorStop(1,f.rf());e.fillStyle=h;d.da(e);e.fill()}if(f=d.sc){d.da(e);e.strokeStyle=f.T;d=f.wc;if(y(d)&&d.indexOf("px")!=-1)d=parseFloat(d)/Of(c);e.lineWidth=d;e.stroke()}}c.getContext().restore()}}
a=sg.prototype;a.v=function(c,d){d=d||this.w;d.appendChild(c);this.L&&!this.Pe&&!(d!=this.w&&d!=this.Ie)&&mg(this,c)};a.Yb=function(c,d,e,f,h,g,l){c=new ng(null,this,c,d,e,f,h,g);this.v(c,l);return c};a.Zb=function(c,d,e,f,h,g,l){c=new pg(null,this,c,d,e,f,h,g);this.v(c,l);return c};a.drawImage=function(c,d,e,f,h,g){c=new rg(null,this,c,d,e,f,h);this.v(c,g);return c};a.$b=function(c,d,e,f,h,g,l,n,m,o){c=new qg(this,c,d,e,f,h,g,l,n,m);this.v(c,o);return c};
a.Ca=function(c,d,e,f){c=new og(null,this,c,d,e);this.v(c,f);return c};a.k=function(){this.Oa=null;sg.m.k.call(this)};a.xa=function(){var c=this.R();sg.m.xa.call(this);if(!c){ug(this);this.dispatchEvent("resize")}lg(this)};/*
 Copyright 2010 Paul Novak (paul@wingu.com)

 Licensed under the Apache License, Version 2.0 (the "License"); you may not
 use this file except in compliance with the License. You may obtain a copy of
 the License at

 http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 License for the specific language governing permissions and limitations under
 the License.
*/
function X(c,d){this.lc=c;this.id=c.id;this.pf=Od(c);this.ic=[];this.Y={};this.Ta={};for(var e in bd)this.Ta[e]=[];this.c=new J(vg);d&&this.c.La(d);d=c.clientWidth;c=c.clientHeight;c=L?new bg(d,c,void 0,void 0,void 0):Wb&&(!N("420")||Xb)?new sg(d,c,void 0,void 0,void 0):new Pf(d,c,void 0,void 0,void 0);c.U();this.l=c;this.l.q(this.lc);this.Ib=new Te(this.l,this.c);this.Vc=this.Xc=false;this.Qa=new Bd(this);this.ld=new rd(document);this.$e=[];wg(this,"keydown",this.hb);wg(this,"keypress",this.If);
wg(this,"keyup",this.Kf);wg(this,"mousedown",this.Ae);wg(this,"mousemove",this.Ce);wg(this,"mouseup",this.Pc);wg(this,"paste",this.De);Lc(this.ld,"shortcut",this.ze,undefined,this);this.ce&&this.eg()&&ae(this.ce,this.e());this.dispatchEvent("load");for(var f in this.Y)Yc(this.Y[f],this);this.Gb=xg;this.Vc=this.Xc=false;this.selected=[];this.kc=[]}var yg;z(X,Vc);v("specview.controller.Controller",X,void 0);function zg(c){yg=c}
X.prototype.clear=function(){this.n.info("Clearing graphics");this.l.clear();this.ic=[new Y];this.kc=new We([],1,0.5);var c=new qe(this.c.f("background").color);this.l.Zb(0,0,this.l.fb().width,this.l.fb().height,null,c)};function Ag(c,d){c.clear();c.ic=d;d=Xa(D(d,function(e){if(e instanceof Y)return Ze([e])}));if(d.length>0)c.kc=new We(d,1,0.5);c.q()}X.prototype.Ve=function(c){Ag(this,c)};v("specview.controller.Controller.prototype.setModels",X.prototype.Ve,void 0);
X.prototype.q=function(){C(this.ic,function(c){c instanceof Y&&this.Ib.q(c)},this)};v("specview.controller.Controller.prototype.render",X.prototype.q,void 0);X.prototype.ib=function(c){for(var d=this.Ta[c],e=Ua(arguments,1),f=0;f<d.length;++f){var h=d[f];if(((h.s==this?h.ac:false)||ad[c])&&h[bd[c]].apply(h,e))return true}return false};X.prototype.fe=function(){this.n.info("disablePlugins");for(var c in this.Y)Zc(this.Y[c],this)};
v("specview.controller.Controller.prototype.disablePlugins",X.prototype.fe,void 0);X.prototype.ge=function(){this.n.info("enablePlugins");for(var c in this.Y)Yc(this.Y[c],this)};v("specview.controller.Controller.prototype.enablePlugins",X.prototype.ge,void 0);
function fd(c,d){c=Bg(c,d);d=La(c,function(e){return e instanceof P});if(d.length>0)return d[0];d=La(c,function(e){return e instanceof Q});if(d.length>0)return d[0];d=La(c,function(e){return e instanceof Y});if(d.length>0)return d[0];d=La(c,function(e){return e instanceof jd.ff});if(d.length>0)return d[0];c=La(c,function(e){return e instanceof jd.lf});if(c.length>0)return c[0]}
function Cg(c,d,e){d-=c.offsetLeft;for(e-=c.offsetTop;c=c.offsetParent;){d-=c.offsetLeft;e-=c.offsetTop}return new I(d,e)}function Bg(c,d){d=bb(c.Ib.transform.Cc(),[Cg(d.currentTarget,d.clientX+document.body.scrollLeft+document.documentElement.scrollLeft,d.clientY+document.body.scrollTop+document.documentElement.scrollTop)])[0];return Ye(c.kc,{x:d.x,y:d.y})}a=X.prototype;a.Ce=function(c){try{this.ib(12,c)}catch(d){this.n.info(d)}};a.Pc=function(c){this.ib(9,c)};a.Ae=function(){};
a.Pc=function(c){this.ib(9,c)};a.ze=function(c){this.ib(5,c)};a.De=function(c){this.ib(25,c)};function Dg(c,d,e){c=c.Ta[7];for(d=0;d<c.length;++d);return e?null:false}function cd(c){C(c.Ta[7],function(d){d.Re&&d.Re()})}X.prototype.queryCommandValue=function(c){var d=this.Cb();if(y(c))return Dg(this,c,d);else{for(var e={},f=0;f<c.length;f++)e[c[f]]=Dg(this,c[f],d);return e}};X.prototype.execCommand=function(){for(var c=this.Ta[6],d=0;d<c.length;++d);};
X.prototype.Qe=function(c){var d=c.we();this.Y[d]&&Hb(this.n,"Cannot register the same class of plugin twice ["+d+"]");this.Y[d]=c;for(var e in bd)c[bd[e]]&&this.Ta[e].push(c);Xc(c,this);this.Cb()&&Yc(c,this)};v("specview.controller.Controller.prototype.registerPlugin",X.prototype.Qe,void 0);X.prototype.Cb=function(){return this.Gb==xg};var xg=2;X.prototype.n=Kb("specview.controller.Controller");var dd="cvc";
X.prototype.k=function(){if(this.Gb==1||this.Cb())this.n.log(Bb,"Disposing an editor that is in use.",void 0);this.lc&&this.execCommand(Eg.gf);for(var c in this.Y){var d=this.Y[c];d.Sd()||Zc(d,this)}this.Gb=0;this.Qa&&this.Qa.Lb();this.ag=null;if(this.Qa){this.Qa.pa();this.Qa=null}for(;c=this.$e.pop();)c.pa();yg==this.id&&zg(null);for(var e in this.Y){c=this.Y[e];c.Zd&&c.pa()}delete this.Y;X.m.k.call(this)};X.prototype.Cb=function(){return this.Gb==xg};
function wg(c,d,e,f,h){Dd(c.Qa,c.lc,d,e,f,h)}X.prototype.mc=function(c,d){this.ld.mc(c,d)};var vg={background:{color:"#F0FFF0"},margin:{left:1,right:1,top:1,bottom:1}};function Fg(c){for(var d=[],e=0,f=c.length;e<f;e++){var h=c[e];h instanceof Array?d.push(Fg(h)):d.push(h)}return d}function Gg(c,d,e){if(c.length)c.push(d[0].concat(e[0]));else c[0]=d[0].concat(e[0])}function Hg(c,d){return c.Cnum-d.Cnum}
function Ig(c,d,e,f){for(var h=0,g=d.length;h<g;h++){var l=d[h];if(c.length>=l.length){for(var n=true,m=0,o=l.length;m<o;m++)E(c,l[m])||(n=false);if(n)return true}m=0;for(o=c.length;m<o;m++)E(l,c[m])&&f[m]++}d=false;m=0;for(o=c.length;m<o;m++)if(f[c[m]]<e[c[m]]-1)d=true;if(d){m=0;for(o=c.length;m<o;m++)f[c[m]]++;return false}return true}
function Jg(c,d,e,f,h){for(var g=[],l=0,n=c.length;l<n;l++){var m=e.g[c[l]],o=Z(e,m.source);m=Z(e,m.target);E(g,o)||g.push(o);E(g,m)||g.push(m)}if(c.length===g.length)Ig(g,d,f,h)||d.push(g)}function Kg(c,d){for(var e=[c[0]],f=d.o(c[0]),h=0;c.length!=e.length;){h++;if(h>1E3)break;for(var g=1,l=c.length;g<l;g++){var n=d.o(e[e.length-1]),m=d.o(c[g]);if(!E(e,c[g]))if(Lg(d,n,m))e.push(c[g]);else Lg(d,f,m)&&Oa(e,c[g],0)}}return e}
function Mg(c){var d=c.$()-c.b.length+1;if(!d)return[];var e;e=c.b.length;for(var f=[],h=0;h<e;h++){for(var g=[],l=0;l<e;l++)if(h==l)g.push(0);else Lg(c,c.o(h),c.o(l))?g.push(1):g.push(99999999);f.push(g)}h=[];for(g=0;g<e;g++){l=[];for(var n=0;n<e;n++){var m=Lg(c,c.o(g),c.o(n));m?l.push([[Ka(c.g,m)]]):l.push([])}h.push(l)}g=[];for(l=0;l<e;l++){n=[];for(m=0;m<e;m++)n.push([]);g.push(n)}for(l=0;l<e;l++)for(n=0;n<e;n++)for(m=0;m<e;m++){var o=f[n][m],q=f[n][l]+f[l][m],s=h[n][l],u=h[l][m];if(q!=1E8)if(o>
q){g[n][m]=o==q+1?Fg(h[n][m]):[];f[n][m]=q;h[n][m]=[s[0].concat(u[0])]}else if(o==q)s.length&&u.length&&Gg(h[n][m],s,u);else if(o==q-1)Gg(g[n][m],s,u);else f[n][m]=f[n][m]}e={D:f,Pe1:h,Pe2:g};f=e.D;h=e.Pe1;g=e.Pe2;l=f.length;e=[];for(n=0;n<l;n++)for(m=0;m<l;m++)f[n][m]==0||h[n][m].length==1&&g[n][m].length==0||e.push({Cnum:g[n][m].length?2*(f[n][m]+0.5):2*f[n][m],Pe1:h[n][m],Pe2:g[n][m]});e.sort(Hg);a:{f=[];h=[];g=0;for(l=c.b.length;g<l;g++)h.push(c.o(g).$());n=[];for(g=0;g<c.b.length;g++)n[g]=0;
g=0;for(l=e.length;g<l;g++){m=e[g];if(m.Cnum%2){o=0;for(q=m.Pe2.length;o<q;o++){s=m.Pe1[0].concat(m.Pe2[o]);Jg(s,f,c,h,n);if(f.length==d){d=f;break a}}}else{o=0;for(q=m.Pe1.length-1;o<q;o++){s=m.Pe1[o].concat(m.Pe1[o+1]);Jg(s,f,c,h,n);if(f.length==d){d=f;break a}}}}d=f}e=0;for(f=d.length;e<f;e++)d[e]=Kg(d[e],c);return d}v("specview.ring.SSSR.findRings",Mg,void 0);function Ng(c,d){for(var e=[],f=0,h=c.length;f<h;f++)e.push(d.o(c[f]));c=[];f=0;for(h=e.length-1;f<h;f++){var g=Lg(d,e[f],e[f+1]);g!=null&&c.push(g)}g=Lg(d,e[0],e[e.length-1]);g!=null&&c.push(g);return new kd(e,c)}
function Og(c){if(!(c.$()-c.b.length+c.tb))return[];for(var d=0,e=c.b.length;d<e;d++){var f=c.b[d];f.index=d;f.ka=undefined;f.Ua=undefined;c.b[d].index=d}d=0;for(e=c.g.length;d<e;d++)c.g[d].index=d;if(e=c.b.length){d=Wa(false,e);e=Wa(false,e);f=[];var h=c.b[0];h.ka=0;f.push(h);for(d[0]=true;;){if(!f.length)break;h=f[0];Ra(f,0);for(var g=h.g.V(),l=0,n=g.length;l<n;l++){var m=g[l],o=m.index;if(!e[o]){e[o]=true;var q=He(m,h);m=q.index;if(d[m]){m=[];if(h.ka==q.ka){m.push(h);m.push(q)}else{q.Ua=true;var s=
Ge(q);o=0;for(var u=s.length;o<u;o++){var w=s[o];w.ka==q.ka-1&&m.push(w)}}for(q=h.ka;;){m[0].Ua=true;m[1].Ua=true;q--;s=Ge(m[0]);o=0;for(u=s.length;o<u;o++)if(s[o].ka==q){m[0]=s[o];break}s=Ge(m[1]);o=0;for(u=s.length;o<u;o++)if(s[o].ka==q){m[1]=s[o];break}if(m[0]==m[1]){m[0].Ua=true;break}}}else{q.ka=h.ka+1;d[m]=true;f.push(q)}}}}}d=[];h=c.b.length;e=Wa(false,h);f=Wa(false,h);h=Wa(-1,h);g=0;for(l=c.b.length;g<l;g++){m=c.b[g];if(!e[m.index])if(m.Ua){n=new Y;u=[];u.push(m);e[0]=true;w=new P;w.yb=m.index;
h[m.index]=0;for(n.va(w);;){if(!u.length)break;q=u[0];Ra(u,0);s=q.g.V();m=0;for(o=s.length;m<o;m++){var K=s[m];w=K.index;if(!f[w]){f[w]=true;K=He(K,q);w=K.index;if(K.Ua){if(e[w]){w=Lg(c,q,K);var aa=new Q(n.b[h[q.index]],n.b[h[K.index]]);aa.yb=w.index}else{e[w]=true;u.push(K);w=new P;w.yb=K.index;h[K.index]=n.b.length;n.va(w);K=Lg(c,q,K);aa=new Q(n.b[h[q.index]],w);aa.yb=K.index}n.bb(aa)}}}}m=0;for(o=n.b.length;m<o;m++)n.b[m].index=m;m=0;for(o=n.g.length;m<o;m++)n.g[m].index=m;m=n.g.length-n.b.length+
1;o=[];u=new ld(n);q=0;for(s=n.b.length;q<s;q++){w=u.remove(n.o(q),6);for(K=0;K<w.length;K++){aa=w[K].b;Ra(aa,aa.length-1);for(var Cc=0,Yg=aa.length;Cc<Yg;Cc++)aa[Cc]=Z(n,aa[Cc]);o.push(aa)}}Ia(o.length!=null);B.sort.call(o,Va);if(o.length>=m){a:{u=[];q=[];s=0;for(w=n.b.length;s<w;s++)q.push(n.o(s).$());K=Wa(0,n.b.length);s=0;for(w=o.length;s<w;s++){aa=o[s];if(!Ig(aa,u,q,K)){u.push(aa);if(u.length==m){u=u;break a}}}u=u}if(u.length<m)u=Mg(n)}else u=Mg(n);m=0;for(o=u.length;m<o;m++){q=u[m];s=0;for(w=
q.length;s<w;s++)q[s]=n.b[q[s]].yb}m=0;for(n=u.length;m<n;m++)d.push(Ng(u[m],c))}}return d}v("specview.ring.RingFinder.findRings",Og,void 0);function Y(c){this.g=[];this.b=[];this.name=c?c:"";this.qd=[];this.jc=true;this.ea=[];this.tb=0}v("specview.model.Molecule",Y,void 0);Y.prototype.bb=function(c){var d=Z(this,c.source),e=Z(this,c.target);if(this.ea[d]!=this.ea[e]){var f;if(this.ea[d]<this.ea[e]){d=this.ea[d];f=this.ea[e]}else{f=this.ea[d];d=this.ea[e]}this.tb--;e=0;for(var h=this.b.length;e<h;e++)if(this.ea[e]==d)this.ea[e]=f}this.g.push(c);c.source.g.add(c);c.target.g.add(c);this.va(c.source);this.va(c.target);c.Wa=this};
v("specview.model.Molecule.prototype.addBond",Y.prototype.bb,void 0);Y.prototype.o=function(c){return this.b[c]};v("specview.model.Molecule.prototype.getAtom",Y.prototype.o,void 0);function Lg(c,d,e){c=d.g.V();for(var f=0,h=c.length;f<h;f++){var g=c[f];if(He(g,d)==e)return g}return null}function Z(c,d){return Ka(c.b,d)}Y.prototype.be=function(){return this.b.length};v("specview.model.Molecule.prototype.countAtoms",Y.prototype.be,void 0);Y.prototype.$=function(){return this.g.length};
v("specview.model.Molecule.prototype.countBonds",Y.prototype.$,void 0);Y.prototype.va=function(c){if(!E(this.b,c)){var d=this.b.length;this.tb++;this.ea[d]=this.tb;this.b.push(c);c.Wa=this}};v("specview.model.Molecule.prototype.addAtom",Y.prototype.va,void 0);function De(c){if(c.jc){c.qd=Og(c);c.jc=false}return c.qd}Y.prototype.K=function(){var c=new Y(this.name);C(this.b,function(d){c.va(d)});C(this.g,function(d){c.bb(d)});return c};
Y.prototype.toString=function(){return"specview.model.Molecule - name: "+this.name+"\n\t"+D(this.b,function(c){return" "+Z(this,c)+": "+c.toString()},this).join("\n\t")+"\n\t"+D(this.g,function(c){return" "+Z(this,c.source)+", "+Z(this,c.target)+":  "+c.toString()},this).join("\n\t")+"\n\t"+D(De(this),function(c){return c.toString()}).join("\n\t")};Y.prototype.la=function(){var c=Pg(this);return new I((c.left+c.right)/2,(c.top+c.bottom)/2)};
function Pg(c){return Jd.apply(null,D(c.b,function(d){return d.a}))}Y.prototype.rotate=function(c,d){var e=$a(new G,F(c),d.x,d.y);C(this.b,function(f){f.a=H(e,[f.a])[0]})};Y.prototype.scale=function(c){var d=ab(new G,c,c);C(this.b,function(e){e.a=H(d,[e.a])[0]})};Y.prototype.translate=function(c){C(this.b,function(d){d.a=S(d.a,c)})};Y.prototype.n=Kb("specview.model.Molecule");function Qg(c){c=String(c);if(/^\s*$/.test(c)?false:/^[\],:{}\s\u2028\u2029]*$/.test(c.replace(/\\["\\\/bfnrtu]/g,"@").replace(/"[^"\\\n\r\u2028\u2029\x00-\x08\x10-\x1f\x80-\x9f]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,"]").replace(/(?:^|:|,)(?:[\s\u2028\u2029]*\[)+/g,"")))try{return eval("("+c+")")}catch(d){}throw Error("Invalid JSON string: "+c);}function Rg(){}
function Sg(c,d,e){switch(typeof d){case "string":Tg(c,d,e);break;case "number":e.push(isFinite(d)&&!isNaN(d)?d:"null");break;case "boolean":e.push(d);break;case "undefined":e.push("null");break;case "object":if(d==null){e.push("null");break}if(ga(d)){var f=d.length;e.push("[");for(var h="",g=0;g<f;g++){e.push(h);Sg(c,d[g],e);h=","}e.push("]");break}e.push("{");f="";for(h in d)if(d.hasOwnProperty(h)){g=d[h];if(typeof g!="function"){e.push(f);Tg(c,h,e);e.push(":");Sg(c,g,e);f=","}}e.push("}");break;
case "function":break;default:throw Error("Unknown type: "+typeof d);}}var Ug={'"':'\\"',"\\":"\\\\","/":"\\/","\u0008":"\\b","\u000c":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\u000b":"\\u000b"},Vg=/\uffff/.test("\uffff")?/[\\\"\x00-\x1f\x7f-\uffff]/g:/[\\\"\x00-\x1f\x7f-\xff]/g;function Tg(c,d,e){e.push('"',d.replace(Vg,function(f){if(f in Ug)return Ug[f];var h=f.charCodeAt(0),g="\\u";if(h<16)g+="000";else if(h<256)g+="00";else if(h<4096)g+="0";return Ug[f]=g+h.toString(16)}),'"')};/*
 Copyright 2010 Paul Novak (paul@wingu.com)

 Licensed under the Apache License, Version 2.0 (the "License"); you may not
 use this file except in compliance with the License. You may obtain a copy of
 the License at

 http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 License for the specific language governing permissions and limitations under
 the License.
*/
function Wg(c){if(c.ga==Ie)return"SINGLE_BOND";if(c.ga==2)return"DOUBLE_BOND";if(c.ga==3)return"TRIPLE_BOND";if(c.ga==4)return"QUADRUPLE_BOND";throw new Error("Invalid bond type ["+c.toString()+"]");}function Xg(c){if(c.ua==11)return"SINGLE_BOND_UP";if(c.ua==13)return"SINGLE_BOND_DOWN";if(c.ua==12)return"SINGLE_BOND_UP_OR_DOWN";return"NOT_STEREO"}
function Zg(c,d,e,f){switch(c){case "SINGLE_BOND":switch(d){case "NOT_STEREO":return new Q(e,f);case "SINGLE_BOND_UP":return new Q(e,f,Ie,11);case "SINGLE_BOND_UP_OR_DOWN":return new Q(e,f,Ie,12);case "SINGLE_BOND_DOWN":return new Q(e,f,Ie,13);default:throw new Error("invalid bond type/stereo ["+c+"]/["+d+"]");}case "DOUBLE_BOND":return new Q(e,f,2);case "TRIPLE_BOND":return new Q(e,f,3);case "QUADRUPLE_BOND":return new Q(e,f,4);case "AROMATIC":return new Q(e,f,undefined,undefined,true);case "SINGLE_OR_DOUBLE":case "SINGLE_OR_AROMATIC":case "DOUBLE_OR_AROMATIC":case "ANY":default:throw new Error("invalid bond type/stereo ["+
c+"]/["+d+"]");}}v("specview.io.json.readMolecule",function(c){c=c.constructor==String?Qg(c):c;var d=new Y;d.name=c.name;C(c.atoms,function(e){d.va(new P(e.symbol,e.coord.x,e.coord.y,e.charge))});C(c.bondindex,function(e){d.bb(Zg(e.type,e.stereo,d.o(e.source),d.o(e.target)))});return d},void 0);v("specview.io.json.writeMolecule",function(c){var d=new Rg;c=$g(c);var e=[];Sg(d,c,e);return e.join("")},void 0);
function $g(c){var d=D(c.b,function(f){return{symbol:f.B,coord:{x:f.a.x,y:f.a.y},charge:f.Q}}),e=D(c.g,function(f){var h=Wg(f),g=Xg(f),l=Z(c,f.source),n=Z(c,f.target);Ia(l>-1);Ia(n>-1);return{source:Z(c,f.source),target:Z(c,f.target),type:h,stereo:g}});return{name:c.name,atoms:d,bondindex:e}}Kb("specview.io.json");var Eg={};var $={Ad:["BC","AD"],zd:["Before Christ","Anno Domini"],Cd:["J","F","M","A","M","J","J","A","S","O","N","D"],Kd:["J","F","M","A","M","J","J","A","S","O","N","D"],Bd:["January","February","March","April","May","June","July","August","September","October","November","December"],Jd:["January","February","March","April","May","June","July","August","September","October","November","December"],Gd:["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"],Nd:["Jan","Feb","Mar","Apr","May",
"Jun","Jul","Aug","Sep","Oct","Nov","Dec"],Qd:["Sunday","Monday","Tuesday","Wednesday","Thursday","Friday","Saturday"],Pd:["Sunday","Monday","Tuesday","Wednesday","Thursday","Friday","Saturday"],Id:["Sun","Mon","Tue","Wed","Thu","Fri","Sat"],Od:["Sun","Mon","Tue","Wed","Thu","Fri","Sat"],kf:["S","M","T","W","T","F","S"],Ld:["S","M","T","W","T","F","S"],Hd:["Q1","Q2","Q3","Q4"],Dd:["1st quarter","2nd quarter","3rd quarter","4th quarter"],yd:["AM","PM"],yc:["EEEE, MMMM d, y","MMMM d, y","MMM d, y",
"M/d/yy"],Ac:["h:mm:ss a zzzz","h:mm:ss a z","h:mm:ss a","h:mm a"],ef:{Md:"M/d",MMMMd:"MMMM d",MMMd:"MMM d"},hf:6,mf:[5,6],jf:2};function ah(){}function bh(c){if(typeof c=="number"){var d=new ah;d.rc=c;d.td=ch(c);c=c;if(c==0)c="UTC";else{var e=["UTC",c<0?"+":"-"];c=Math.abs(c);e.push(Math.floor(c/60)%100);c%=60;c!=0&&e.push(":",c);c=e.join("")}d.tc=[c,c];d.Mb=[];return d}d=new ah;d.td=c.id;d.rc=-c.std_offset;d.tc=c.names;d.Mb=c.transitions;return d}function dh(c){var d=["GMT"];d.push(c<=0?"+":"-");c=Math.abs(c);d.push(A(Math.floor(c/60)%100,2),":",A(c%60,2));return d.join("")}
function ch(c){if(c==0)return"Etc/GMT";var d=["Etc/GMT",c<0?"-":"+"];c=Math.abs(c);d.push(Math.floor(c/60)%100);c%=60;c!=0&&d.push(":",A(c,2));return d.join("")}function eh(c,d){d=Date.UTC(d.getUTCFullYear(),d.getUTCMonth(),d.getUTCDate(),d.getUTCHours(),d.getUTCMinutes())/36E5;for(var e=0;e<c.Mb.length&&d>=c.Mb[e];)e+=2;return e==0?0:c.Mb[e-1]}function fh(c,d){c=-(c.rc-eh(c,d));d=[c<0?"-":"+"];c=Math.abs(c);d.push(A(Math.floor(c/60)%100,2),A(c%60,2));return d.join("")};function gh(c){Ia(c!==undefined,"Pattern must be defined");this.Kb=[];typeof c=="number"?hh(this,c):ih(this,c)}var jh=[/^\'(?:[^\']|\'\')*\'/,/^(?:G+|y+|M+|k+|S+|E+|a+|h+|K+|H+|c+|L+|Q+|d+|m+|s+|v+|z+|Z+)/,/^[^\'GyMkSEahKHcLQdmsvzZ]+/];function ih(c,d){for(;d;)for(var e=0;e<jh.length;++e){var f=d.match(jh[e]);if(f){f=f[0];d=d.substring(f.length);if(e==0)if(f=="''")f="'";else{f=f.substring(1,f.length-1);f=f.replace(/\'\'/,"'")}c.Kb.push({text:f,type:e});break}}}
function hh(c,d){if(d<4)d=$.yc[d];else if(d<8)d=$.Ac[d-4];else if(d<12)d=$.yc[d-8]+" "+$.Ac[d-8];else{hh(c,10);return}ih(c,d)}
function kh(c,d,e,f,h,g){c=d.length;switch(d.charAt(0)){case "G":e=f.getFullYear()>0?1:0;return c>=4?$.zd[e]:$.Ad[e];case "y":e=f.getFullYear();if(e<0)e=-e;return c==2?A(e%100,2):String(e);case "M":a:{e=f.getMonth();switch(c){case 5:c=$.Cd[e];break a;case 4:c=$.Bd[e];break a;case 3:c=$.Gd[e];break a;default:c=A(e+1,c);break a}}return c;case "k":return A(h.getHours()||24,c);case "S":return(h.getTime()%1E3/1E3).toFixed(Math.min(3,c)).substr(2)+(c>3?A(0,c-3):"");case "E":e=f.getDay();return c>=4?$.Qd[e]:
$.Id[e];case "a":c=h.getHours();return $.yd[c>=12&&c<24?1:0];case "h":return A(h.getHours()%12||12,c);case "K":return A(h.getHours()%12,c);case "H":return A(h.getHours(),c);case "c":a:{e=f.getDay();switch(c){case 5:c=$.Ld[e];break a;case 4:c=$.Pd[e];break a;case 3:c=$.Od[e];break a;default:c=A(e,1);break a}}return c;case "L":a:{e=f.getMonth();switch(c){case 5:c=$.Kd[e];break a;case 4:c=$.Jd[e];break a;case 3:c=$.Nd[e];break a;default:c=A(e+1,c);break a}}return c;case "Q":e=Math.floor(f.getMonth()/
3);return c<4?$.Hd[e]:$.Dd[e];case "d":return A(f.getDate(),c);case "m":return A(h.getMinutes(),c);case "s":return A(h.getSeconds(),c);case "v":c=(c=g)||bh(e.getTimezoneOffset());return c.td;case "z":d=(d=g)||bh(e.getTimezoneOffset());return c<4?d.tc[eh(d,e)>0?2:0]:d.tc[eh(d,e)>0?3:1];case "Z":d=(d=g)||bh(e.getTimezoneOffset());return c<4?fh(d,e):dh(d.rc-eh(d,e));default:return""}};var lh=3;lh=3;function mh(c){if(c.Ma)return 4;if(c.ga==Ie)return 1;if(c.ga==2)return 2;if(c.ga==3)return lh;throw new Error("Invalid bond type ["+c+"]");}function nh(c){if(c.ua==11)return 1;if(c.ua==13)return 6;if(c.ua==12)return 4;return 0}
function oh(c,d,e,f){switch(c){case 1:switch(d){case 0:return new Q(e,f);case 1:return new Q(e,f,Ie,11);case 4:return new Q(e,f,Ie,12);case 6:return new Q(e,f,Ie,13);default:throw new Error("invalid bond type/stereo ["+c+"]/["+d+"]");}case 2:return new Q(e,f,2);case lh:return new Q(e,f,3);case 4:c=new Q(e,f);c.Ma=true;return c;case 5:throw new Error("type not implemented ["+c+"]");case 6:throw new Error("type not implemented ["+c+"]");case 7:throw new Error("type not implemented ["+c+"]");case 8:throw new Error("type not implemented ["+
c+"]");default:throw new Error("invalid bond type/stereo ["+c+"]/["+d+"]");}}
v("specview.io.mdl.readMolfile",function(c){c=c.split(c.indexOf("\r\n")>0?"\r\n":"\n");for(var d=new Y(c[0]),e=parseInt(c[3].substr(0,3),10),f=parseInt(c[3].substr(3,3),10),h=1;h<=e;h++){var g=c[h+3],l=g.substr(30,4).replace(/(^\s*)|(\s*$)/g,""),n=parseFloat(g.substr(0,10)),m=parseFloat(g.substr(10,10));g=parseInt(g.substr(36,3),10);var o=0;if(g!=0)if(g==1)o=3;else if(g==2)o=2;else if(g==3)o=1;else if(g!=4)if(g==5)o=-1;else if(g==6)o=-2;else if(g==7)o=-3;g=new P(l,n,m,o);d.va(g)}for(h=1;h<=f;h++){g=
c[h+3+e];o=d.o(parseInt(g.substr(0,3),10)-1);l=d.o(parseInt(g.substr(3,3),10)-1);g=oh(parseInt(g.substr(6,3),10),parseInt(g.substr(9,3),10),o,l);d.bb(g)}h=4+e+f;e=c.length;for(f=false;;){g=c[h++];if(h==e||g.indexOf("M  END")>=0)break;if(g.indexOf("M  CHG")>=0){if(!f){o=0;for(f=d.b.length;o<f;o++)d.o(o).Q=0;f=true}l=parseInt(g.substr(6,3),10);for(n=0;n<l;n++){m=parseInt(g.substr(10+8*n,3),10);o=parseInt(g.substr(14+8*n,3),10);d.o(m-1).Q=o}}}return d},void 0);
v("specview.io.mdl.writeMolfile",function(c){var d="",e="",f="",h=d="";e=new Date;f=c.name+"\n";for(var g=new gh("mmddyyHHMM"),l=[],n=0;n<g.Kb.length;++n){var m=g.Kb[n].text;1==g.Kb[n].type?l.push(kh(g,m,e,e,e,void 0)):l.push(m)}e=f+(" JChemHub"+l.join("")+"\n")+"\n";f=(Ca(" ",3)+c.b.length).slice(-3);g=(Ca(" ",3)+c.$()).slice(-3);f=f+g+"  0  0  0  0            999 V2000\n";for(i=0;i<c.b.length;i++){m=c.o(i);g=(Ca(" ",10)+m.a.x.toFixed(4)).slice(-10);l=(Ca(" ",10)+m.a.y.toFixed(4)).slice(-10);n=(Ca(" ",
10)+(0).toFixed(4)).slice(-10);m=(Ca(" ",3)+m.B).slice(-3);d+=g+l+n+m+"\n"}for(i=0;i<c.$();i++){g=c.g[i];l=Z(c,g.source)+1;l=(Ca(" ",3)+l).slice(-3);n=Z(c,g.target)+1;n=(Ca(" ",3)+n).slice(-3);m=(Ca(" ",3)+mh(g)).slice(-3);g=(Ca(" ",3)+nh(g)).slice(-3);h+=l+n+m+g+"\n"}return d=e+f+d+h+"M  END\n"},void 0);
