/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("uk.ac.ebi.metabolights.java-conventions")
    id("project-report")
    war
}

dependencies {
    api("javax.mail:mail:1.4.5")
    api("uk.ac.ebi:ebinocle:1.0.4")
    api("uk.ac.ebi.biobabel:ebeye-client:2.0.0")
    api(project(":metabolights-referencelayer-dao"))
    api("uk.ac.ebi.biobabel:biobabel-citations:2.0.3")
    api(project(":metabolights-ws-client"))
    api(project(":metabolights-isatab-utils"))
    api(project(":referencelayer-importer"))
    api("org.json:json:20090211")
    api("org.apache.logging.log4j:log4j-web:2.16.0")
    api("org.slf4j:jcl-over-slf4j:1.7.0")
    api("org.springframework:spring-context:4.3.30.RELEASE")
    api("org.springframework:spring-aop:4.3.30.RELEASE")
    api("org.springframework:spring-orm:4.3.30.RELEASE")
    api("org.springframework:spring-web:4.3.30.RELEASE")
    api("org.springframework.security:spring-security-core:4.2.20.RELEASE")
    api("org.springframework.security:spring-security-config:4.2.20.RELEASE")
    api("org.springframework.security:spring-security-taglibs:4.2.20.RELEASE")
    api("org.springframework:spring-beans:4.3.30.RELEASE")
    api("org.springframework:spring-context-support:4.3.30.RELEASE")
    api("org.springframework:spring-webmvc:4.3.30.RELEASE")
    api("org.springframework:spring-core:4.3.30.RELEASE")
    api("org.springframework.session:spring-session-data-redis:1.3.5.RELEASE")
    api("biz.paluch.redis:lettuce:3.4.3.Final")
    api("org.hibernate:hibernate-core:4.2.11.Final")
    api("org.hibernate:hibernate-validator:4.3.2.Final")
    api("org.postgresql:postgresql:9.4-1200-jdbc41")
    api("org.apache.tiles:tiles-jsp:2.2.2")
    api("javax.validation:validation-api:1.0.0.GA")
    api("org.apache.commons:commons-compress:1.3")
    api("commons-fileupload:commons-fileupload:1.2.2")
    api("commons-dbcp:commons-dbcp:1.4")
    api("org.apache.velocity:velocity:1.7")
    api("javax.persistence:persistence-api:1.0.2")
    api("javax.servlet:jstl:1.2")
    api("org.glassfish.web:jstl-impl:1.2")
    api("commons-httpclient:commons-httpclient:3.1")
    testImplementation("rhino:js:1.7R2")
    testImplementation("org.mozilla:rhino:1.7R3")
    testImplementation("net.sourceforge.jwebunit:jwebunit-htmlunit-plugin:2.5")
    providedCompile("javax.servlet:javax.servlet-api:3.0.1")
}

description = "metabolights Web Application"
