/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("uk.ac.ebi.metabolights.java-conventions")
}


dependencies {
    // api("org.apache.commons:com.springsource.org.apache.commons.httpclient:3.1.0")
    api("org.isatools:ISAcreator-api:1.7.7.2-SNAPSHOT"){
        exclude(group = "org.isatools", module = "ISAtabErrorReporter")
        exclude(group = "org.isatools", module = "import_layer_MTBLS_API")
        exclude(group = "org.apache.commons", module = "com.springsource.org.apache.commons.httpclient")
    }
    api(project(":metabolights-domain"))
    api(project(":metabolights-isatab-utils"))

    api("org.hibernate:hibernate-core:4.3.8.Final")
    // api("org.hibernate:hibernate-core:5.6.15.Final")

    api("net.sourceforge.javacsv:javacsv:2.0")
    api("org.codehaus.jtstand:jtstand-sequence:1.2.1")
    api("com.fasterxml.jackson.core:jackson-core:2.8.9")
    api("com.fasterxml.jackson.core:jackson-databind:2.8.9")
    api(project(":metabolights-ws-client"))
    api("org.postgresql:postgresql:42.6.0")
    testImplementation("org.dbunit:dbunit:2.5.1")
    runtimeOnly("org.apache.tomcat:tomcat-catalina:9.0.73")

}

description = "MetaboLights DAO"
