/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("uk.ac.ebi.metabolights.java-conventions")
}


dependencies {
    api("org.isatools:ISAcreator-api:1.7.7.2-SNAPSHOT")
    api(project(":metabolights-domain"))
    api(project(":metabolights-isatab-utils"))
    api("org.hibernate:hibernate-core:4.3.8.Final")
    api("net.sourceforge.javacsv:javacsv:2.0")
    api("org.codehaus.jtstand:jtstand-sequence:1.2.1")
    api("com.fasterxml.jackson.core:jackson-core:2.8.9")
    api("com.fasterxml.jackson.core:jackson-databind:2.8.9")
    api(project(":metabolights-ws-client"))
    testImplementation("org.postgresql:postgresql:9.4-1200-jdbc41")
    testImplementation("org.dbunit:dbunit:2.5.1")
    testImplementation("org.apache.tomcat:tomcat-catalina:8.0.18")
}

description = "MetaboLights DAO"
