/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("uk.ac.ebi.metabolights.java-conventions")
}

dependencies {
    api(project(":metabolights-ws-client"))
    api(project(":metabolights-domain"))
}

description = "metabolights-export"
