/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("uk.ac.ebi.metabolights.java-conventions")
}

dependencies {
    api(project(":metabolights-domain"))
    api("com.fasterxml.jackson.core:jackson-core:2.8.9")
    api("com.fasterxml.jackson.core:jackson-databind:2.8.9")
    api(project(":search-service"))
}

description = "MetaboLights webservice client"
