/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("uk.ac.ebi.metabolights.java-conventions")
}

dependencies {
    api(project(":metabolights-domain"))
    api("commons-io:commons-io:2.7")
    api("com.fasterxml.jackson.core:jackson-core:2.8.9")
    api("com.fasterxml.jackson.core:jackson-databind:2.8.9")
    api(project(":search-service"))
    // api("org.apache.logging.log4j:log4j-core:2.17.2")
    api("org.json:json:20090211")
    // api("org.apache.logging.log4j:log4j-core:2.17.2")
}

description = "MetaboLights webservice client"
