/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("uk.ac.ebi.metabolights.java-conventions")
}

dependencies {
    api("uk.ac.ebi.ols:ols-client:1.18")
    api(project(":species-model"))
    api(project(":WoRMS-client"))
    api(project(":globalnames-client"))
}

description = "MetaboLights Species Core"
