/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("uk.ac.ebi.metabolights.java-conventions")
}

dependencies {
    api("commons-lang:commons-lang:2.5")
}

group = "uk.ac.ebi.metabolights.referencelayer"
description = "MetaboLights Reference Layer Domain"
