/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("uk.ac.ebi.metabolights.java-conventions")
}

dependencies {
    api("com.fasterxml.jackson.core:jackson-databind:2.9.9.2")
    api("org.codehaus.jackson:jackson-core-asl:1.9.13")
    api("commons-httpclient:commons-httpclient:3.1")
}

description = "globalnames-client"
