-- Explore Test metabolites
SELECT * FROM REF_METABOLITE where ACC like '%ACC%';

--Exlore test species
SELECT * from REF_MET_TO_SPECIES S
  LEFT JOIN REF_METABOLITE M ON S.MET_ID = M.ID
  LEFT JOIN REF_XREF X ON S.REF_XREF_ID = X.ID
  LEFT JOIN REF_SPECIES SP ON s.SPECIES_ID = SP.ID
  LEFT JOIN REF_DB D ON X.DB_ID = D.ID
where M.ACC like '%ACC%';

--Exlore test species
SELECT * from REF_MET_SPECTRA S
  LEFT JOIN REF_METABOLITE M ON S.MET_ID = M.ID
  LEFT JOIN REF_ATTRIBUTE ATT ON S.ID = ATT.SPECTRA_ID
where M.ACC like '%ACC%';
