/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    `java-library`
    `maven-publish`
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://www.ebi.ac.uk/~maven/m2repo")
    }

    maven {
        url = uri("https://www.ebi.ac.uk/~biobabel/maven2_repo")
    }

    maven {
        url = uri("https://repository-master.mulesoft.org/nexus/content/groups/public/")
    }

    maven {
        url = uri("https://www.ebi.ac.uk/Tools/maven/repos/content/groups/ebi-repo/")
    }

    maven {
        url = uri("https://mvnrepository.com/artifact/org.jvnet.staxex/stax-ex")
    }

    maven {
        url = uri("https://limpopo.sourceforge.net/maven/repo")
    }

    maven {
        url = uri("https://dist.wso2.org/maven2/")
    }

    maven {
        url = uri("https://repo.springsource.org/release")
    }

    maven {
        url = uri("https://maven.springframework.org/milestone")
    }

    maven {
        url = uri("https://repository.jboss.org/nexus/content/repositories/releases/")
    }

    maven {
        url = uri("https://github.com/biojava/maven-repo/raw/master/")
    }

    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }

    maven {
        url = uri("https://jni-inchi.sourceforge.net/m2repo")

        // isAllowInsecureProtocol = true
    }

    maven {
        url = uri("https://oss.sonatype.org/content/repositories/snapshots/")
    }
}

dependencies {
    api("commons-io:commons-io:2.0.1")
    api("org.slf4j:slf4j-api:1.7.7")
    api("org.jvnet.staxex:stax-ex:1.7.7")
    api("net.bull.javamelody:javamelody-core:1.69.0")
    testImplementation("junit:junit:4.8.2")
    testImplementation("org.apache.logging.log4j:log4j-slf4j-impl:2.16.0")
    testImplementation("org.apache.logging.log4j:log4j-core:2.16.0")
}

group = "uk.ac.ebi.metabolights"
version = "3.0"
java.sourceCompatibility = JavaVersion.VERSION_1_7

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}
