/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    `java-library`
    `maven-publish`
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://mvnrepository.com/artifact/")
    }
    
    maven {
        url = uri("https://www.ebi.ac.uk/~maven/m2repo")
    }

    maven {
        url = uri("https://www.ebi.ac.uk/~biobabel/maven2_repo")
    }

    // maven {
    //     url = uri("https://repository-master.mulesoft.org/nexus/content/groups/public/")
    // }

    maven {
        url = uri("https://www.ebi.ac.uk/Tools/maven/repos/content/groups/ebi-repo/")
    }

    maven {
        url = uri("https://limpopo.sourceforge.net/maven/repo")
    }

    maven {
        url = uri("https://dist.wso2.org/maven2/")
    }

    maven {
        url = uri("https://repository.jboss.org/nexus/content/repositories/releases/")
    }

    maven {
        url = uri("https://github.com/biojava/maven-repo/raw/master/")
    }

    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }

    maven {
        url = uri("https://jni-inchi.sourceforge.net/m2repo")

        // isAllowInsecureProtocol = true
    }

    maven {
        url = uri("https://oss.sonatype.org/content/repositories/snapshots/")
    }


    flatDir {
        dirs("libs")
    }
}

dependencies {
    api("commons-io:commons-io:2.7")
    api("org.apache.logging.log4j:log4j-slf4j-impl:2.17.2")
    api("org.apache.logging.log4j:log4j-core:2.17.2")
    api("org.apache.logging.log4j:log4j-web:2.17.2")
//    api("org.slf4j:slf4j-api:2.0.7")
    api("org.apache.logging.log4j:log4j-jcl:2.17.2")
    api("org.jvnet.staxex:stax-ex:1.7.7") {
        exclude("org.slf4j:slf4j-api:1.7.7")
    }
    api("net.bull.javamelody:javamelody-core:1.69.0")
    testImplementation("junit:junit:4.8.2")
}

configurations.all {
  resolutionStrategy {
    force("org.jvnet.staxex:stax-ex:1.7.8")
    force("jakarta.servlet:jakarta.servlet-api:4.0.4")
  }
}

tasks.withType<Copy> {
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}

group = "uk.ac.ebi.metabolights"
version = "3.0"
// java.sourceCompatibility = JavaVersion.VERSION_1_7
// java.targetCompatibility = JavaVersion.VERSION_1_7
java.sourceCompatibility = JavaVersion.VERSION_1_8
java.targetCompatibility = JavaVersion.VERSION_1_8

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}
