set scan off;

truncate table REF_MET_PATHWAYS;
drop table REF_MET_PATHWAYS purge;

DROP SEQUENCE REF_MET_PATHWAYS_SEQ;

CREATE SEQUENCE REF_MET_PATHWAYS_SEQ INCREMENT BY 1 START WITH 1 NOCACHE;

CREATE TABLE REF_MET_PATHWAYS(
  ID NUMBER NOT NULL 
, PATHWAY_DB_ID NUMBER NOT NULL
, MET_ID NUMBER NOT NULL
, NAME VARCHAR(50) NOT NULL
, PATH_TO_PATHWAY_FILE VARCHAR2(4000)
, SPECIES_ID NUMBER NOT NULL
, CONSTRAINT REF_MET_PATHWAYS_PK PRIMARY KEY(ID) ENABLE
, CONSTRAINT REF_MET_PATHWAYS_DB_FK FOREIGN KEY (PATHWAY_DB_ID) REFERENCES ISATAB.REF_DB (ID)
, CONSTRAINT REF_MET_PATHWAYS_MET_FK FOREIGN KEY (MET_ID) REFERENCES ISATAB.REF_METABOLITE (ID) ON DELETE CASCADE ENABLE
, CONSTRAINT REF_MET_PATHWAYS_SPECIES_FK FOREIGN KEY (SPECIES_ID) REFERENCES ISATAB.REF_SPECIES (ID)
);

CREATE OR REPLACE TRIGGER ISATAB.REF_MET_PATHWAYS_TRG 
   before insert on ISATAB.REF_MET_PATHWAYS 
   for each row 
begin  
   if inserting then 
      if :NEW.ID is null then 
         select REF_MET_PATHWAYS_SEQ.nextval into :NEW.ID from dual; 
      end if; 
   end if; 
end;
/

ALTER TRIGGER ISATAB.REF_MET_PATHWAYS_TRG ENABLE;


