/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("uk.ac.ebi.metabolights.java-conventions")
}

dependencies {
    api(project(":metabolights-referencelayer-dao"))
    api(project(":metabolights-ws-client"))
    api("uk.ac.ebi.mdk:mdk-service-soap:1.4.1")
    api("org.biojava:biojava3-core:3.0.7")
    api(project(":species-core"))
    api("org.apache.httpcomponents:httpclient:4.3.5")
    api("org.postgresql:postgresql:42.6.0")
    api("com.google.guava:guava:10.0")
}

group = "uk.ac.ebi.metabolights.referencelayer"
description = "MetaboLights Reference layer importer"
