/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("uk.ac.ebi.metabolights.java-conventions")
}

dependencies {
    api("net.sf.opencsv:opencsv:2.1")
    api("uk.ac.ebi.pride:jmztab:2.1.8")
    api("net.sf.jni-inchi:jni-inchi:0.7")
    api(project(":metabolights-dao"))
}

description = "MetaboLights mzTab Imp/Exp"
