/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("uk.ac.ebi.metabolights.java-conventions")
}

dependencies {
    api("com.fasterxml.jackson.core:jackson-annotations:2.8.9")
    api(project(":metabolights-domain"))
    api("com.google.guava:guava:22.0")
}

description = "MetaboLights Search Service"
