/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("uk.ac.ebi.metabolights.java-conventions")
}

dependencies {
    api(project(":search-service"))
    api("org.elasticsearch:elasticsearch:1.4.1")
    api("com.google.code.gson:gson:2.1")
    api("com.fasterxml.jackson.core:jackson-core:2.8.9")
    api("com.fasterxml.jackson.core:jackson-databind:2.8.9")
    api("org.postgresql:postgresql:42.6.0")
    testImplementation(project(":metabolights-dao"))
}

description = "MetaboLights Search Service - ES"
